image: golang:1.25.7-trixie

stages:
  - test

unit_tests:
  stage: test
  variables:
    HTTP_PROXY: proxy.uni-leipzig.de:3128
    HTTPS_PROXY: proxy.uni-leipzig.de:3128
  before_script:
    - go version
    # zstd is used by the crossref snapshot code under test
    - DEBIAN_FRONTEND=noninteractive apt-get update --yes && apt-get install --yes zstd
  script:
    - go vet ./...
    - go tool staticcheck ./...
    - go test -race ./...
  tags:
    - docker
