package crossrefcmd

import (
	"bytes"
	"fmt"
	"io"
	"log"
	"net/http"
	"net/url"
	"time"

	"github.com/segmentio/encoding/json"
)

// MembersResponse from api.crossref.org/member, generated by JSONGen, use offset to paginate.
type MembersResponse struct {
	Message struct {
		Items []struct {
			Breakdowns any `json:"breakdowns"`
			Counts     struct {
				BackfileDois int64 `json:"backfile-dois"`
				CurrentDois  int64 `json:"current-dois"`
				TotalDois    int64 `json:"total-dois"`
			} `json:"counts"`
			CountsType   any `json:"counts-type"`
			Coverage     any `json:"coverage"`
			CoverageType any `json:"coverage-type"`
			Flags        struct {
				Deposits                           bool `json:"deposits"`
				DepositsAbstractsBackfile          bool `json:"deposits-abstracts-backfile"`
				DepositsAbstractsCurrent           bool `json:"deposits-abstracts-current"`
				DepositsAffiliationsBackfile       bool `json:"deposits-affiliations-backfile"`
				DepositsAffiliationsCurrent        bool `json:"deposits-affiliations-current"`
				DepositsArticles                   bool `json:"deposits-articles"`
				DepositsAwardNumbersBackfile       bool `json:"deposits-award-numbers-backfile"`
				DepositsAwardNumbersCurrent        bool `json:"deposits-award-numbers-current"`
				DepositsFundersBackfile            bool `json:"deposits-funders-backfile"`
				DepositsFundersCurrent             bool `json:"deposits-funders-current"`
				DepositsLicensesBackfile           bool `json:"deposits-licenses-backfile"`
				DepositsLicensesCurrent            bool `json:"deposits-licenses-current"`
				DepositsOpenReferencesBackfile     bool `json:"deposits-open-references-backfile"`
				DepositsOpenReferencesCurrent      bool `json:"deposits-open-references-current"`
				DepositsOrcidsBackfile             bool `json:"deposits-orcids-backfile"`
				DepositsOrcidsCurrent              bool `json:"deposits-orcids-current"`
				DepositsReferencesBackfile         bool `json:"deposits-references-backfile"`
				DepositsReferencesCurrent          bool `json:"deposits-references-current"`
				DepositsResourceLinksBackfile      bool `json:"deposits-resource-links-backfile"`
				DepositsResourceLinksCurrent       bool `json:"deposits-resource-links-current"`
				DepositsSimilarityCheckingBackfile bool `json:"deposits-similarity-checking-backfile"`
				DepositsSimilarityCheckingCurrent  bool `json:"deposits-similarity-checking-current"`
				DepositsUpdatePoliciesBackfile     bool `json:"deposits-update-policies-backfile"`
				DepositsUpdatePoliciesCurrent      bool `json:"deposits-update-policies-current"`
			} `json:"flags"`
			Id                  int64    `json:"id"`
			LastStatusCheckTime int64    `json:"last-status-check-time"`
			Location            string   `json:"location"`
			Names               []string `json:"names"`
			Prefix              []struct {
				Name                string `json:"name"`
				PublicReferences    bool   `json:"public-references"`
				ReferenceVisibility string `json:"reference-visibility"`
				Value               string `json:"value"`
			} `json:"prefix"`
			Prefixes    []string `json:"prefixes"`
			PrimaryName string   `json:"primary-name"`
			Tokens      []string `json:"tokens"`
		} `json:"items"`
		ItemsPerPage int64 `json:"items-per-page"`
		Query        struct {
			SearchTerms any   `json:"search-terms"`
			StartIndex  int64 `json:"start-index"`
		} `json:"query"`
		TotalResults int64 `json:"total-results"`
	} `json:"message"`
	MessageType    string `json:"message-type"`
	MessageVersion string `json:"message-version"`
	Status         string `json:"status"`
}

// MembersConfig holds the pagination options for RunMembers.
type MembersConfig struct {
	Offset     int
	Rows       int
	Base       string
	Sleep      time.Duration
	RetryCount int
}

// DefaultMembersConfig returns the default configuration.
func DefaultMembersConfig() MembersConfig {
	return MembersConfig{
		Offset:     0,
		Rows:       20,
		Base:       "http://api.crossref.org/members",
		Sleep:      1 * time.Second,
		RetryCount: 3,
	}
}

// HTTPGetter fetches a URL. It is injected so RunMembers can be tested without
// hitting the network; the default is http.Get.
type HTTPGetter func(url string) (*http.Response, error)

// RunMembers paginates through the crossref members API and writes one raw
// response per line to w. On HTTP >= 400 it retries (up to cfg.RetryCount)
// with a fixed backoff.
func RunMembers(cfg MembersConfig, get HTTPGetter, w io.Writer) error {
	if get == nil {
		get = http.Get
	}
	offset := cfg.Offset
	var buf bytes.Buffer
	for {
		v := url.Values{}
		v.Add("offset", fmt.Sprintf("%d", offset))
		v.Add("rows", fmt.Sprintf("%d", cfg.Rows))
		link := fmt.Sprintf("%s?%s", cfg.Base, v.Encode())

		// Why: Because an HTTP 500 appeared, which for some reason did not persist.
		var (
			retries int
			resp    *http.Response
			err     error
		)
		for {
			if retries > cfg.RetryCount {
				return fmt.Errorf("retry count exceeded")
			}
			log.Println(link)
			resp, err = get(link)
			if err != nil {
				return err
			}
			if resp.StatusCode < 400 {
				break
			}
			log.Printf("request failed with HTTP %d", resp.StatusCode)
			resp.Body.Close()
			time.Sleep(2 * time.Second)
			retries++
		}

		tee := io.TeeReader(resp.Body, &buf)

		// Need to peek into offset and total results.
		dec := json.NewDecoder(tee)
		var mr MembersResponse
		if err := dec.Decode(&mr); err != nil {
			log.Printf("decode failed: %s", buf.String())
			resp.Body.Close()
			return err
		}
		resp.Body.Close()
		if mr.Status != "ok" {
			return fmt.Errorf("status not ok: %s", mr.Status)
		}
		if mr.Message.Query.StartIndex >= mr.Message.TotalResults {
			break
		}
		log.Printf("done: %d/%d", mr.Message.Query.StartIndex, mr.Message.TotalResults)

		time.Sleep(cfg.Sleep)
		offset = offset + cfg.Rows

		fmt.Fprintln(w, buf.String())
		buf.Truncate(0)
	}
	return nil
}
