package finc

import "github.com/miku/span/container"

var SubjectMapping = container.StringSliceMap{
	"Accounting":                       []string{"Wirtschaftswissenschaften"},
	"Acoustics and Ultrasonics":        []string{"Physik"},
	"Advanced and Specialised Nursing": []string{"Medizin"},
	"Aerospace Engineering":            []string{"Technik"},
	"Ageing":                           []string{"Medizin"},
	"Agricultural and Biological Sciences (miscellaneous)": []string{"Land- und Forstwirtschaft, Gartenbau, Fischereiwirtschaft, Hauswirtschaft"},
	"Agricultural and Biological Sciences(all)":            []string{"Land- und Forstwirtschaft, Gartenbau, Fischereiwirtschaft, Hauswirtschaft"},
	"Agronomy and Crop Science":                            []string{"Land- und Forstwirtschaft, Gartenbau, Fischereiwirtschaft, Hauswirtschaft"},
	"Algebra and Number Theory":                            []string{"Mathematik"},
	"Analysis":                                             []string{"Mathematik"},
	"Analytical Chemistry":                                 []string{"Chemie und Pharmazie"},
	"Anatomy":                                              []string{"Medizin"},
	"Anesthesiology and Pain Medicine":                     []string{"Medizin"},
	"Animal Science and Zoology":                           []string{"Biologie"},
	"Anthropology":                                         []string{"Ethnologie (Volks- und Völkerkunde)"},
	"Applied Mathematics":                                  []string{"Mathematik"},
	"Applied Microbiology and Biotechnology":               []string{"Biologie", "Technik"},
	"Applied Psychology":                                   []string{"Psychologie"},
	"Aquatic Science":                                      []string{"Biologie"},
	"Archaeology":                                          []string{"Klassische Archäologie"},
	"Architecture":                                         []string{"Technik"},
	"Artificial Intelligence":                              []string{"Informatik"},
	"Arts and Humanities (miscellaneous)":                  []string{"Kunst und Kunstgeschichte"},
	"Arts and Humanities(all)":                             []string{"Kunst und Kunstgeschichte"},
	"Assessment and Diagnosis":                             []string{"Medizin"},
	"Astronomy and Astrophysics":                           []string{"Physik"},
	"Atmospheric Science":                                  []string{"Physik"},
	"Atomic and Molecular Physics, and Optics":             []string{"Physik"},
	"Automotive Engineering":                               []string{"Technik"},
	"Behavioral Neuroscience":                              []string{"Medizin"},
	"Biochemistry":                                         []string{"Chemie und Pharmazie"},
	"Biochemistry, Genetics and Molecular Biology (miscellaneous)": []string{"Chemie und Pharmazie", "Biologie"},
	"Biochemistry, Genetics and Molecular Biology(all)":            []string{"Chemie und Pharmazie", "Biologie"},
	"Biochemistry, medical":                                        []string{"Chemie und Pharmazie", "Biologie"},
	"Bioengineering":                                               []string{"Biologie", "Chemie und Pharmazie", "Technik"},
	"Biological Psychiatry":                                        []string{"Biologie", "Psychologie"},
	"Biomaterials":                                                 []string{"Biologie", "Technik"},
	"Biomedical Engineering":                                       []string{"Biologie", "Medizin", "Technik"},
	"Biophysics":                                                   []string{"Biologie", "Physik"},
	"Biotechnology":                                                []string{"Biologie", "Technik"},
	"Building and Construction":                                    []string{"Technik"},
	"Business and International Management":                        []string{"Wirtschaftswissenschaften"},
	"Business, Management and Accounting (miscellaneous)":          []string{"Wirtschaftswissenschaften"},
	"Business, Management and Accounting(all)":                     []string{"Wirtschaftswissenschaften"},
	"Cancer Research":                                              []string{"Medizin"},
	"Cardiology and Cardiovascular Medicine":                       []string{"Medizin"},
	"Care Planning":                                                []string{"Medizin"},
	"Catalysis":                                                    []string{"Chemie und Pharmazie"},
	"Cell Biology":                                                 []string{"Biologie"},
	"Cellular and Molecular Neuroscience":                          []string{"Biologie", "Psychologie"},
	"Ceramics and Composites":                                      []string{"Technik"},
	"Chemical Engineering (miscellaneous)":                         []string{"Chemie und Pharmazie", "Technik"},
	"Chemical Engineering(all)":                                    []string{"Chemie und Pharmazie", "Technik"},
	"Chemical Health and Safety":                                   []string{"Chemie und Pharmazie", "Technik", "Medizin"},
	"Chemistry (miscellaneous)":                                    []string{"Chemie und Pharmazie", "Technik"},
	"Chemistry(all)":                                               []string{"Chemie und Pharmazie", "Technik"},
	"Chiropractics":                                                []string{"Medizin"},
	"Civil and Structural Engineering":                             []string{"Technik"},
	"Classics":                                                     []string{"Philosophie", "Klassische Philologie"},
	"Clinical Biochemistry":                                        []string{"Medizin", "Biologie", "Chemie und Pharmazie"},
	"Clinical Neurology":                                           []string{"Medizin", "Biologie"},
	"Clinical Psychology":                                          []string{"Medizin", "Biologie", "Psychologie"},
	"Cognitive Neuroscience":                                       []string{"Medizin", "Biologie", "Psychologie"},
	"Colloid and Surface Chemistry":                                []string{"Chemie und Pharmazie"},
	"Communication":                                                []string{"Philosophie", "Technik"},
	"Community and Home Care":                                      []string{"Allgemeines"},
	"Complementary and Manual Therapy":                             []string{"Medizin"},
	"Complementary and alternative medicine":                       []string{"Medizin"},
	"Computational Mathematics":                                    []string{"Mathematik"},
	"Computational Mechanics":                                      []string{"Physik"},
	"Computational Theory and Mathematics":                         []string{"Mathematik"},
	"Computer Graphics and Computer-Aided Design":                  []string{"Informatik"},
	"Computer Networks and Communications":                         []string{"Informatik"},
	"Computer Science (miscellaneous)":                             []string{"Informatik"},
	"Computer Science Applications":                                []string{"Informatik"},
	"Computer Science(all)":                                        []string{"Informatik"},
	"Computer Vision and Pattern Recognition":                      []string{"Informatik"},
	"Computers in Earth Sciences":                                  []string{"Informatik", "Geographie", "Geologie und Paläontologie"},
	"Condensed Matter Physics":                                     []string{"Physik"},
	"Conservation":                                                 []string{"Allgemeines"},
	"Control and Optimization":                                     []string{"Mathematik", "Technik"},
	"Control and Systems Engineering":                              []string{"Technik"},
	"Critical Care":                                                []string{"Medizin"},
	"Critical Care and Intensive Care Medicine":                    []string{"Medizin"},
	"Cultural Studies":                                             []string{"Allgemeines"},
	"Decision Sciences (miscellaneous)":                            []string{"Mathematik", "Technik"},
	"Decision Sciences(all)":                                       []string{"Mathematik", "Technik"},
	"Demography":                                                   []string{"Allgemeines"},
	"Dental Assisting":                                             []string{"Medizin"},
	"Dental Hygiene":                                               []string{"Medizin"},
	"Dentistry (miscellaneous)":                                    []string{"Medizin"},
	"Dentistry(all)":                                               []string{"Medizin"},
	"Dermatology":                                                  []string{"Medizin"},
	"Development":                                                  []string{"Allgemeines"},
	"Developmental Biology":                                        []string{"Biologie"},
	"Developmental Neuroscience":                                   []string{"Biologie", "Psychologie"},
	"Developmental and Educational Psychology":                     []string{"Biologie", "Psychologie"},
	"Discrete Mathematics and Combinatorics":                       []string{"Mathematik", "Informatik"},
	"Drug Discovery":                                               []string{"Chemie und Pharmazie"},
	"Drug guides":                                                  []string{"Chemie und Pharmazie"},
	"Earth and Planetary Sciences (miscellaneous)":                 []string{"Geologie und Paläontologie", "Geographie"},
	"Earth and Planetary Sciences(all)":                            []string{"Geologie und Paläontologie", "Geographie"},
	"Earth-Surface Processes":                                      []string{"Geologie und Paläontologie", "Geographie"},
	"Ecological Modelling":                                         []string{"Geologie und Paläontologie", "Geographie", "Physik"},
	"Ecology":                                                      []string{"Geographie"},
	"Ecology, Evolution, Behavior and Systematics":        []string{"Geographie"},
	"Economic Geology":                                    []string{"Geographie", "Wirtschaftswissenschaften"},
	"Economics and Econometrics":                          []string{"Wirtschaftswissenschaften"},
	"Economics, Econometrics and Finance (miscellaneous)": []string{"Wirtschaftswissenschaften"},
	"Economics, Econometrics and Finance(all)":            []string{"Wirtschaftswissenschaften"},
	"Education":                                           []string{"Pädagogik"},
	"Electrical and Electronic Engineering":               []string{"Technik", "Mathematik", "Physik"},
	"Electrochemistry":                                    []string{"Technik", "Physik", "Chemie und Pharmazie"},
	"Electronic, Optical and Magnetic Materials":          []string{"Technik", "Physik"},
	"Embryology":                                          []string{"Medizin", "Biologie"},
	"Emergency":                                           []string{"Medizin"},
	"Emergency Medicine":                                  []string{"Medizin"},
	"Endocrine and Autonomic Systems":                     []string{"Medizin"},
	"Endocrinology":                                       []string{"Medizin"},
	"Endocrinology, Diabetes and Metabolism":              []string{"Medizin"},
	"Energy (miscellaneous)":                              []string{"Physik"},
	"Energy Engineering and Power Technology":             []string{"Physik"},
	"Energy(all)":                                         []string{"Physik"},
	"Engineering (miscellaneous)":                         []string{"Technik"},
	"Engineering(all)":                                    []string{"Technik"},
	"Environmental Chemistry":                             []string{"Technik", "Chemie und Pharmazie"},
	"Environmental Engineering":                           []string{"Technik", "Geographie", "Biologie"},
	"Environmental Science (miscellaneous)":               []string{"Technik", "Geographie", "Biologie"},
	"Environmental Science(all)":                          []string{"Technik", "Geographie", "Biologie"},
	"Epidemiology":                                        []string{"Medizin"},
	"Equine":                                              []string{"Biologie"},
	"Experimental and Cognitive Psychology": []string{"Psychologie"},
	"Family Practice":                       []string{"Allgemeines", "Psychologie"},
	"Filtration and Separation":             []string{"Chemie und Pharmazie"},
	"Finance":                               []string{"Wirtschaftswissenschaften"},
	"Fluid Flow and Transfer Processes":     []string{"Physik"},
	"Food Animals":                          []string{"Land- und Forstwirtschaft, Gartenbau, Fischereiwirtschaft, Hauswirtschaft"},
	"Food Science":                          []string{"Land- und Forstwirtschaft, Gartenbau, Fischereiwirtschaft, Hauswirtschaft"},
	"Forestry":                              []string{"Land- und Forstwirtschaft, Gartenbau, Fischereiwirtschaft, Hauswirtschaft"},
	"Fuel Technology":                       []string{"Technik"},
	"Fundamentals and skills":               []string{"Pädagogik"},
	"Gastroenterology":                      []string{"Medizin"},
	"Gender Studies":                        []string{"Allgemeines", "Philosophie"},
	"General":                               []string{"Allgemeines"},
	"Genetics":                              []string{"Biologie"},
	"Genetics(clinical)":                    []string{"Biologie", "Medizin"},
	"Geochemistry and Petrology":            []string{"Geologie und Paläontologie", "Geographie", "Chemie und Pharmazie"},
	"Geography, Planning and Development":   []string{"Geographie"},
	"Geology":               []string{"Geologie und Paläontologie"},
	"Geometry and Topology": []string{"Mathematik"},
	"Geophysics":            []string{"Geologie und Paläontologie", "Geographie", "Physik"},
	"Geotechnical Engineering and Engineering Geology": []string{"Geologie und Paläontologie", "Geographie", "Technik"},
	"Geriatrics and Gerontology":                       []string{"Medizin"},
	"Gerontology":                                      []string{"Medizin"},
	"Global and Planetary Change":                      []string{"Geologie und Paläontologie", "Geographie", "Physik"},
	"Hardware and Architecture":                        []string{"Technik"},
	"Health Informatics":                               []string{"Medizin", "Informatik"},
	"Health Information Management":                    []string{"Medizin", "Informatik"},
	"Health Policy":                                    []string{"Medizin"},
	"Health Professions (miscellaneous)":               []string{"Medizin"},
	"Health Professions(all)":                          []string{"Medizin"},
	"Health(social science)":                           []string{"Medizin"},
	"Health, Toxicology and Mutagenesis":               []string{"Medizin"},
	"Hematology":                                       []string{"Medizin"},
	"Hepatology":                                       []string{"Medizin"},
	"Histology":                                        []string{"Biologie"},
	"History":                                          []string{"Geschichte"},
	"History and Philosophy of Science":                []string{"Geschichte", "Philosophie"},
	"Horticulture":                                     []string{"Land- und Forstwirtschaft, Gartenbau, Fischereiwirtschaft, Hauswirtschaft"},
	"Human Factors and Ergonomics":                     []string{"Allgemeines"},
	"Human-Computer Interaction":                       []string{"Informatik"},
	"Immunology":                                       []string{"Medizin"},
	"Immunology and Allergy":                           []string{"Medizin"},
	"Immunology and Microbiology (miscellaneous)":      []string{"Medizin"},
	"Immunology and Microbiology(all)":                 []string{"Medizin"},
	"Industrial and Manufacturing Engineering":         []string{"Technik"},
	"Industrial relations":                             []string{"Technik"},
	"Infectious Diseases":                              []string{"Medizin"},
	"Information Systems":                              []string{"Informatik"},
	"Information Systems and Management":               []string{"Informatik"},
	"Inorganic Chemistry":                              []string{"Chemie und Pharmazie"},
	"Insect Science":                                   []string{"Biologie"},
	"Instrumentation":                                  []string{"Allgemeines", "Technik"},
	"Internal Medicine":                                []string{"Medizin"},
	"Issues, ethics and legal aspects":                 []string{"Rechtswissenschaft"},
	"LPN and LVN":                                      []string{"Medizin"},
	"Language and Linguistics":                         []string{"Allgemeine und vergleichende Sprach- und Literaturwissenschaft", "Indogermanistik", "Außereuropäische Sprachen und Literaturen"},
	"Law": []string{"Rechtswissenschaft"},
	"Leadership and Management":         []string{"Wirtschaftswissenschaften"},
	"Library and Information Sciences":  []string{"Allgemeines"},
	"Life-span and Life-course Studies": []string{"Medizin"},
	"Linguistics and Language":          []string{"Allgemeine und vergleichende Sprach- und Literaturwissenschaft", "Indogermanistik", "Außereuropäische Sprachen und Literaturen"},
	"Literature and Literary Theory":    []string{"Allgemeine und vergleichende Sprach- und Literaturwissenschaft", "Indogermanistik", "Außereuropäische Sprachen und Literaturen"},
	"Logic": []string{"Mathematik"},
	"Management Information Systems":             []string{"Wirtschaftswissenschaften"},
	"Management Science and Operations Research": []string{"Wirtschaftswissenschaften"},
	"Management of Technology and Innovation":    []string{"Wirtschaftswissenschaften"},
	"Management, Monitoring, Policy and Law":     []string{"Wirtschaftswissenschaften"},
	"Marketing":                                  []string{"Wirtschaftswissenschaften"},
	"Materials Chemistry":                        []string{"Chemie und Pharmazie"},
	"Materials Science (miscellaneous)":          []string{"Technik"},
	"Materials Science(all)":                     []string{"Technik"},
	"Maternity and Midwifery":                    []string{"Medizin"},
	"Mathematical Physics":                       []string{"Mathematik", "Physik"},
	"Mathematics (miscellaneous)":                []string{"Mathematik"},
	"Mathematics(all)":                           []string{"Mathematik"},
	"Mechanical Engineering":                     []string{"Technik"},
	"Mechanics of Materials":                     []string{"Technik"},
	"Media Technology":                           []string{"Allgemeines", "Technik"},
	"Medical Laboratory Technology":              []string{"Medizin", "Technik"},
	"Medical–Surgical":                           []string{"Medizin"},
	"Medicine (miscellaneous)":                   []string{"Medizin"},
	"Medicine(all)":                              []string{"Medizin"},
	"Metals and Alloys":                          []string{"Chemie und Pharmazie"},
	"Microbiology":                               []string{"Biologie"},
	"Microbiology (medical)":                     []string{"Biologie"},
	"Modelling and Simulation":                   []string{"Technik"},
	"Molecular Biology":                          []string{"Biologie"},
	"Molecular Medicine":                         []string{"Medizin"},
	"Museology":                                  []string{"Allgemeines"},
	"Music":                                      []string{"Musikwissenschaft"},
	"Nature and Landscape Conservation": []string{"Geographie", "Biologie"},
	"Nephrology":                        []string{"Medizin"},
	"Neurology":                         []string{"Medizin"},
	"Neuropsychology and Physiological Psychology":               []string{"Medizin", "Psychologie"},
	"Neuroscience (miscellaneous)":                               []string{"Medizin"},
	"Neuroscience(all)":                                          []string{"Medizin"},
	"Nuclear Energy and Engineering":                             []string{"Physik", "Technik"},
	"Nuclear and High Energy Physics":                            []string{"Physik", "Technik"},
	"Numerical Analysis":                                         []string{"Mathematik"},
	"Nurse Assisting":                                            []string{"Medizin"},
	"Nursing (miscellaneous)":                                    []string{"Medizin"},
	"Nursing(all)":                                               []string{"Medizin"},
	"Nutrition and Dietetics":                                    []string{"Medizin"},
	"Obstetrics and Gynaecology":                                 []string{"Medizin"},
	"Occupational Therapy":                                       []string{"Medizin"},
	"Ocean Engineering":                                          []string{"Allgemeine Naturwissenschaft"},
	"Oceanography":                                               []string{"Allgemeine Naturwissenschaft"},
	"Oncology":                                                   []string{"Medizin"},
	"Oncology(nursing)":                                          []string{"Medizin"},
	"Ophthalmology":                                              []string{"Medizin"},
	"Optometry":                                                  []string{"Medizin"},
	"Oral Surgery":                                               []string{"Medizin"},
	"Organic Chemistry":                                          []string{"Chemie und Pharmazie"},
	"Organizational Behavior and Human Resource Management":      []string{"Wirtschaftswissenschaften"},
	"Orthodontics":                                               []string{"Medizin"},
	"Orthopedics and Sports Medicine":                            []string{"Medizin"},
	"Otorhinolaryngology":                                        []string{"Medizin"},
	"Palaeontology":                                              []string{"Geologie und Paläontologie"},
	"Parasitology":                                               []string{"Medizin"},
	"Pathology and Forensic Medicine":                            []string{"Medizin"},
	"Pediatrics":                                                 []string{"Medizin"},
	"Pediatrics, Perinatology, and Child Health":                 []string{"Medizin"},
	"Periodontics":                                               []string{"Medizin"},
	"Pharmaceutical Science":                                     []string{"Chemie und Pharmazie"},
	"Pharmacology":                                               []string{"Chemie und Pharmazie"},
	"Pharmacology (medical)":                                     []string{"Chemie und Pharmazie"},
	"Pharmacology (nursing)":                                     []string{"Chemie und Pharmazie"},
	"Pharmacology, Toxicology and Pharmaceutics (miscellaneous)": []string{"Chemie und Pharmazie"},
	"Pharmacology, Toxicology and Pharmaceutics(all)":            []string{"Chemie und Pharmazie"},
	"Pharmacy":                                            []string{"Chemie und Pharmazie"},
	"Philosophy":                                          []string{"Philosophie"},
	"Phychiatric Mental Health":                           []string{"Medizin", "Psychologie"},
	"Physical Therapy, Sports Therapy and Rehabilitation": []string{"Medizin"},
	"Physical and Theoretical Chemistry":                  []string{"Chemie und Pharmazie", "Physik"},
	"Physics and Astronomy (miscellaneous)":               []string{"Physik"},
	"Physics and Astronomy(all)":                          []string{"Physik"},
	"Physiology":                                          []string{"Biologie"},
	"Physiology (medical)":                                []string{"Biologie"},
	"Plant Science":                                       []string{"Biologie"},
	"Podiatry":                                            []string{"Medizin"},
	"Political Science and International Relations": []string{"Politologie"},
	"Pollution":                                            []string{"Geographie"},
	"Polymers and Plastics":                                []string{"Chemie und Pharmazie"},
	"Process Chemistry and Technology":                     []string{"Chemie und Pharmazie", "Technik"},
	"Psychiatry and Mental health":                         []string{"Medizin", "Psychologie"},
	"Psychology (miscellaneous)":                           []string{"Psychologie"},
	"Psychology(all)":                                      []string{"Psychologie"},
	"Public Administration":                                []string{"Allgemeines"},
	"Public Health, Environmental and Occupational Health": []string{"Medizin"},
	"Pulmonary and Respiratory Medicine":                   []string{"Medizin"},
	"Radiation":                                            []string{"Physik"},
	"Radiological and Ultrasound Technology":               []string{"Medizin", "Technik", "Physik"},
	"Radiology Nuclear Medicine and imaging":               []string{"Medizin"},
	"Rehabilitation":                                       []string{"Medizin"},
	"Religious studies":                                    []string{"Theologie und Religionswissenschaft"},
	"Renewable Energy, Sustainability and the Environment": []string{"Geographie", "Technik"},
	"Reproductive Medicine":                                []string{"Medizin"},
	"Research and Theory":                                  []string{"Allgemeines"},
	"Review and Exam Preparation":                          []string{"Allgemeines"},
	"Reviews and References, Medical":                      []string{"Medizin"},
	"Rheumatology":                                         []string{"Medizin"},
	"Safety Research":                                      []string{"Allgemeines"},
	"Safety, Risk, Reliability and Quality":                []string{"Allgemeines"},
	"Sensory Systems":                                      []string{"Technik"},
	"Signal Processing":                                    []string{"Technik"},
	"Small Animals":                                        []string{"Biologie"},
	"Social Psychology":                                    []string{"Psychologie"},
	"Social Sciences (miscellaneous)":                      []string{"Allgemeines"},
	"Social Sciences(all)":                                 []string{"Allgemeines"},
	"Sociology and Political Science":                      []string{"Soziologie"},
	"Software":                                             []string{"Informatik"},
	"Soil Science":                                         []string{"Land- und Forstwirtschaft, Gartenbau, Fischereiwirtschaft, Hauswirtschaft"},
	"Space and Planetary Science":                          []string{"Physik", "Technik"},
	"Spectroscopy":                                         []string{"Physik"},
	"Speech and Hearing":                                   []string{"Allgemeines"},
	"Statistical and Nonlinear Physics":                    []string{"Physik"},
	"Statistics and Probability":                           []string{"Mathematik"},
	"Statistics, Probability and Uncertainty":              []string{"Mathematik"},
	"Strategy and Management":                              []string{"Wirtschaftswissenschaften"},
	"Stratigraphy":                                         []string{"Geographie", "Geologie und Paläontologie"},
	"Structural Biology":                                   []string{"Biologie"},
	"Surfaces and Interfaces":                              []string{"Allgemeines", "Technik"},
	"Surfaces, Coatings and Films":                         []string{"Allgemeines", "Technik"},
	"Surgery":                                              []string{"Medizin"},
	"Theoretical Computer Science":                         []string{"Informatik"},
	"Tourism, Leisure and Hospitality Management":          []string{"Allgemeines"},
	"Toxicology":                                           []string{"Chemie und Pharmazie"},
	"Transplantation":                                      []string{"Medizin"},
	"Transportation":                                       []string{"Allgemeines"},
	"Urban Studies":                                        []string{"Soziologie", "Geographie"},
	"Urology":                                              []string{"Medizin"},
	"Virology":                                             []string{"Medizin"},
	"Visual Arts and Performing Arts":                      []string{"Kunst und Kunstgeschichte"},
	"Waste Management and Disposal":                        []string{"Geographie", "Technik"},
	"Water Science and Technology":                         []string{"Geographie", "Technik"},
	"veterinary (miscalleneous)":                           []string{"Medizin"},
	"veterinary(all)":                                      []string{"Medizin"},
}
