// DO NOT EDIT!
// Code generated by ffjson <https://github.com/pquerna/ffjson>
// source: solr4vu13v1.go
// DO NOT EDIT!

package exporter

import (
	"bytes"
	"fmt"
	fflib "github.com/pquerna/ffjson/fflib/v1"
)

func (mj *Solr4Vufind13v1) MarshalJSON() ([]byte, error) {
	var buf fflib.Buffer
	if mj == nil {
		buf.WriteString("null")
		return buf.Bytes(), nil
	}
	err := mj.MarshalJSONBuf(&buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
func (mj *Solr4Vufind13v1) MarshalJSONBuf(buf fflib.EncodingBuffer) error {
	if mj == nil {
		buf.WriteString("null")
		return nil
	}
	var err error
	var obj []byte
	_ = obj
	_ = err
	buf.WriteString(`{ "format_de15":`)
	if mj.FormatDe15 != nil {
		buf.WriteString(`[`)
		for i, v := range mj.FormatDe15 {
			if i != 0 {
				buf.WriteString(`,`)
			}
			fflib.WriteJsonString(buf, string(v))
		}
		buf.WriteString(`]`)
	} else {
		buf.WriteString(`null`)
	}
	buf.WriteByte(',')
	if len(mj.AccessFacet) != 0 {
		buf.WriteString(`"access_facet":`)
		fflib.WriteJsonString(buf, string(mj.AccessFacet))
		buf.WriteByte(',')
	}
	buf.WriteString(`"author_facet":`)
	if mj.AuthorFacet != nil {
		buf.WriteString(`[`)
		for i, v := range mj.AuthorFacet {
			if i != 0 {
				buf.WriteString(`,`)
			}
			fflib.WriteJsonString(buf, string(v))
		}
		buf.WriteString(`]`)
	} else {
		buf.WriteString(`null`)
	}
	buf.WriteByte(',')
	if len(mj.Allfields) != 0 {
		buf.WriteString(`"allfields":`)
		fflib.WriteJsonString(buf, string(mj.Allfields))
		buf.WriteByte(',')
	}
	if len(mj.Author) != 0 {
		buf.WriteString(`"author":`)
		fflib.WriteJsonString(buf, string(mj.Author))
		buf.WriteByte(',')
	}
	if len(mj.FincClassFacet) != 0 {
		buf.WriteString(`"finc_class_facet":`)
		if mj.FincClassFacet != nil {
			buf.WriteString(`[`)
			for i, v := range mj.FincClassFacet {
				if i != 0 {
					buf.WriteString(`,`)
				}
				fflib.WriteJsonString(buf, string(v))
			}
			buf.WriteString(`]`)
		} else {
			buf.WriteString(`null`)
		}
		buf.WriteByte(',')
	}
	if len(mj.Formats) != 0 {
		buf.WriteString(`"format":`)
		if mj.Formats != nil {
			buf.WriteString(`[`)
			for i, v := range mj.Formats {
				if i != 0 {
					buf.WriteString(`,`)
				}
				fflib.WriteJsonString(buf, string(v))
			}
			buf.WriteString(`]`)
		} else {
			buf.WriteString(`null`)
		}
		buf.WriteByte(',')
	}
	if len(mj.Fullrecord) != 0 {
		buf.WriteString(`"fullrecord":`)
		fflib.WriteJsonString(buf, string(mj.Fullrecord))
		buf.WriteByte(',')
	}
	if len(mj.Fulltext) != 0 {
		buf.WriteString(`"fulltext":`)
		fflib.WriteJsonString(buf, string(mj.Fulltext))
		buf.WriteByte(',')
	}
	if len(mj.HierarchyParentTitle) != 0 {
		buf.WriteString(`"hierarchy_parent_title":`)
		if mj.HierarchyParentTitle != nil {
			buf.WriteString(`[`)
			for i, v := range mj.HierarchyParentTitle {
				if i != 0 {
					buf.WriteString(`,`)
				}
				fflib.WriteJsonString(buf, string(v))
			}
			buf.WriteString(`]`)
		} else {
			buf.WriteString(`null`)
		}
		buf.WriteByte(',')
	}
	if len(mj.ID) != 0 {
		buf.WriteString(`"id":`)
		fflib.WriteJsonString(buf, string(mj.ID))
		buf.WriteByte(',')
	}
	if len(mj.Institutions) != 0 {
		buf.WriteString(`"institution":`)
		if mj.Institutions != nil {
			buf.WriteString(`[`)
			for i, v := range mj.Institutions {
				if i != 0 {
					buf.WriteString(`,`)
				}
				fflib.WriteJsonString(buf, string(v))
			}
			buf.WriteString(`]`)
		} else {
			buf.WriteString(`null`)
		}
		buf.WriteByte(',')
	}
	if len(mj.Imprint) != 0 {
		buf.WriteString(`"imprint":`)
		fflib.WriteJsonString(buf, string(mj.Imprint))
		buf.WriteByte(',')
	}
	if len(mj.ISSN) != 0 {
		buf.WriteString(`"issn":`)
		if mj.ISSN != nil {
			buf.WriteString(`[`)
			for i, v := range mj.ISSN {
				if i != 0 {
					buf.WriteString(`,`)
				}
				fflib.WriteJsonString(buf, string(v))
			}
			buf.WriteString(`]`)
		} else {
			buf.WriteString(`null`)
		}
		buf.WriteByte(',')
	}
	if len(mj.Languages) != 0 {
		buf.WriteString(`"language":`)
		if mj.Languages != nil {
			buf.WriteString(`[`)
			for i, v := range mj.Languages {
				if i != 0 {
					buf.WriteString(`,`)
				}
				fflib.WriteJsonString(buf, string(v))
			}
			buf.WriteString(`]`)
		} else {
			buf.WriteString(`null`)
		}
		buf.WriteByte(',')
	}
	if len(mj.MegaCollections) != 0 {
		buf.WriteString(`"mega_collection":`)
		if mj.MegaCollections != nil {
			buf.WriteString(`[`)
			for i, v := range mj.MegaCollections {
				if i != 0 {
					buf.WriteString(`,`)
				}
				fflib.WriteJsonString(buf, string(v))
			}
			buf.WriteString(`]`)
		} else {
			buf.WriteString(`null`)
		}
		buf.WriteByte(',')
	}
	if mj.PublishDateSort != 0 {
		buf.WriteString(`"publishDateSort":`)
		fflib.FormatBits2(buf, uint64(mj.PublishDateSort), 10, mj.PublishDateSort < 0)
		buf.WriteByte(',')
	}
	if len(mj.Publishers) != 0 {
		buf.WriteString(`"publisher":`)
		if mj.Publishers != nil {
			buf.WriteString(`[`)
			for i, v := range mj.Publishers {
				if i != 0 {
					buf.WriteString(`,`)
				}
				fflib.WriteJsonString(buf, string(v))
			}
			buf.WriteString(`]`)
		} else {
			buf.WriteString(`null`)
		}
		buf.WriteByte(',')
	}
	if len(mj.RecordType) != 0 {
		buf.WriteString(`"recordtype":`)
		fflib.WriteJsonString(buf, string(mj.RecordType))
		buf.WriteByte(',')
	}
	if len(mj.Series) != 0 {
		buf.WriteString(`"series":`)
		if mj.Series != nil {
			buf.WriteString(`[`)
			for i, v := range mj.Series {
				if i != 0 {
					buf.WriteString(`,`)
				}
				fflib.WriteJsonString(buf, string(v))
			}
			buf.WriteString(`]`)
		} else {
			buf.WriteString(`null`)
		}
		buf.WriteByte(',')
	}
	if len(mj.SecondaryAuthors) != 0 {
		buf.WriteString(`"author2":`)
		if mj.SecondaryAuthors != nil {
			buf.WriteString(`[`)
			for i, v := range mj.SecondaryAuthors {
				if i != 0 {
					buf.WriteString(`,`)
				}
				fflib.WriteJsonString(buf, string(v))
			}
			buf.WriteString(`]`)
		} else {
			buf.WriteString(`null`)
		}
		buf.WriteByte(',')
	}
	if len(mj.SourceID) != 0 {
		buf.WriteString(`"source_id":`)
		fflib.WriteJsonString(buf, string(mj.SourceID))
		buf.WriteByte(',')
	}
	if len(mj.Subtitle) != 0 {
		buf.WriteString(`"title_sub":`)
		fflib.WriteJsonString(buf, string(mj.Subtitle))
		buf.WriteByte(',')
	}
	if len(mj.Title) != 0 {
		buf.WriteString(`"title":`)
		fflib.WriteJsonString(buf, string(mj.Title))
		buf.WriteByte(',')
	}
	if len(mj.TitleFull) != 0 {
		buf.WriteString(`"title_full":`)
		fflib.WriteJsonString(buf, string(mj.TitleFull))
		buf.WriteByte(',')
	}
	if len(mj.TitleShort) != 0 {
		buf.WriteString(`"title_short":`)
		fflib.WriteJsonString(buf, string(mj.TitleShort))
		buf.WriteByte(',')
	}
	if len(mj.TitleSort) != 0 {
		buf.WriteString(`"title_sort":`)
		fflib.WriteJsonString(buf, string(mj.TitleSort))
		buf.WriteByte(',')
	}
	if len(mj.Topics) != 0 {
		buf.WriteString(`"topic":`)
		if mj.Topics != nil {
			buf.WriteString(`[`)
			for i, v := range mj.Topics {
				if i != 0 {
					buf.WriteString(`,`)
				}
				fflib.WriteJsonString(buf, string(v))
			}
			buf.WriteString(`]`)
		} else {
			buf.WriteString(`null`)
		}
		buf.WriteByte(',')
	}
	if len(mj.URL) != 0 {
		buf.WriteString(`"url":`)
		if mj.URL != nil {
			buf.WriteString(`[`)
			for i, v := range mj.URL {
				if i != 0 {
					buf.WriteString(`,`)
				}
				fflib.WriteJsonString(buf, string(v))
			}
			buf.WriteString(`]`)
		} else {
			buf.WriteString(`null`)
		}
		buf.WriteByte(',')
	}
	buf.Rewind(1)
	buf.WriteByte('}')
	return nil
}

const (
	ffj_t_Solr4Vufind13v1base = iota
	ffj_t_Solr4Vufind13v1no_such_key

	ffj_t_Solr4Vufind13v1_FormatDe15

	ffj_t_Solr4Vufind13v1_AccessFacet

	ffj_t_Solr4Vufind13v1_AuthorFacet

	ffj_t_Solr4Vufind13v1_Allfields

	ffj_t_Solr4Vufind13v1_Author

	ffj_t_Solr4Vufind13v1_FincClassFacet

	ffj_t_Solr4Vufind13v1_Formats

	ffj_t_Solr4Vufind13v1_Fullrecord

	ffj_t_Solr4Vufind13v1_Fulltext

	ffj_t_Solr4Vufind13v1_HierarchyParentTitle

	ffj_t_Solr4Vufind13v1_ID

	ffj_t_Solr4Vufind13v1_Institutions

	ffj_t_Solr4Vufind13v1_Imprint

	ffj_t_Solr4Vufind13v1_ISSN

	ffj_t_Solr4Vufind13v1_Languages

	ffj_t_Solr4Vufind13v1_MegaCollections

	ffj_t_Solr4Vufind13v1_PublishDateSort

	ffj_t_Solr4Vufind13v1_Publishers

	ffj_t_Solr4Vufind13v1_RecordType

	ffj_t_Solr4Vufind13v1_Series

	ffj_t_Solr4Vufind13v1_SecondaryAuthors

	ffj_t_Solr4Vufind13v1_SourceID

	ffj_t_Solr4Vufind13v1_Subtitle

	ffj_t_Solr4Vufind13v1_Title

	ffj_t_Solr4Vufind13v1_TitleFull

	ffj_t_Solr4Vufind13v1_TitleShort

	ffj_t_Solr4Vufind13v1_TitleSort

	ffj_t_Solr4Vufind13v1_Topics

	ffj_t_Solr4Vufind13v1_URL
)

var ffj_key_Solr4Vufind13v1_FormatDe15 = []byte("format_de15")

var ffj_key_Solr4Vufind13v1_AccessFacet = []byte("access_facet")

var ffj_key_Solr4Vufind13v1_AuthorFacet = []byte("author_facet")

var ffj_key_Solr4Vufind13v1_Allfields = []byte("allfields")

var ffj_key_Solr4Vufind13v1_Author = []byte("author")

var ffj_key_Solr4Vufind13v1_FincClassFacet = []byte("finc_class_facet")

var ffj_key_Solr4Vufind13v1_Formats = []byte("format")

var ffj_key_Solr4Vufind13v1_Fullrecord = []byte("fullrecord")

var ffj_key_Solr4Vufind13v1_Fulltext = []byte("fulltext")

var ffj_key_Solr4Vufind13v1_HierarchyParentTitle = []byte("hierarchy_parent_title")

var ffj_key_Solr4Vufind13v1_ID = []byte("id")

var ffj_key_Solr4Vufind13v1_Institutions = []byte("institution")

var ffj_key_Solr4Vufind13v1_Imprint = []byte("imprint")

var ffj_key_Solr4Vufind13v1_ISSN = []byte("issn")

var ffj_key_Solr4Vufind13v1_Languages = []byte("language")

var ffj_key_Solr4Vufind13v1_MegaCollections = []byte("mega_collection")

var ffj_key_Solr4Vufind13v1_PublishDateSort = []byte("publishDateSort")

var ffj_key_Solr4Vufind13v1_Publishers = []byte("publisher")

var ffj_key_Solr4Vufind13v1_RecordType = []byte("recordtype")

var ffj_key_Solr4Vufind13v1_Series = []byte("series")

var ffj_key_Solr4Vufind13v1_SecondaryAuthors = []byte("author2")

var ffj_key_Solr4Vufind13v1_SourceID = []byte("source_id")

var ffj_key_Solr4Vufind13v1_Subtitle = []byte("title_sub")

var ffj_key_Solr4Vufind13v1_Title = []byte("title")

var ffj_key_Solr4Vufind13v1_TitleFull = []byte("title_full")

var ffj_key_Solr4Vufind13v1_TitleShort = []byte("title_short")

var ffj_key_Solr4Vufind13v1_TitleSort = []byte("title_sort")

var ffj_key_Solr4Vufind13v1_Topics = []byte("topic")

var ffj_key_Solr4Vufind13v1_URL = []byte("url")

func (uj *Solr4Vufind13v1) UnmarshalJSON(input []byte) error {
	fs := fflib.NewFFLexer(input)
	return uj.UnmarshalJSONFFLexer(fs, fflib.FFParse_map_start)
}

func (uj *Solr4Vufind13v1) UnmarshalJSONFFLexer(fs *fflib.FFLexer, state fflib.FFParseState) error {
	var err error = nil
	currentKey := ffj_t_Solr4Vufind13v1base
	_ = currentKey
	tok := fflib.FFTok_init
	wantedTok := fflib.FFTok_init

mainparse:
	for {
		tok = fs.Scan()
		//	println(fmt.Sprintf("debug: tok: %v  state: %v", tok, state))
		if tok == fflib.FFTok_error {
			goto tokerror
		}

		switch state {

		case fflib.FFParse_map_start:
			if tok != fflib.FFTok_left_bracket {
				wantedTok = fflib.FFTok_left_bracket
				goto wrongtokenerror
			}
			state = fflib.FFParse_want_key
			continue

		case fflib.FFParse_after_value:
			if tok == fflib.FFTok_comma {
				state = fflib.FFParse_want_key
			} else if tok == fflib.FFTok_right_bracket {
				goto done
			} else {
				wantedTok = fflib.FFTok_comma
				goto wrongtokenerror
			}

		case fflib.FFParse_want_key:
			// json {} ended. goto exit. woo.
			if tok == fflib.FFTok_right_bracket {
				goto done
			}
			if tok != fflib.FFTok_string {
				wantedTok = fflib.FFTok_string
				goto wrongtokenerror
			}

			kn := fs.Output.Bytes()
			if len(kn) <= 0 {
				// "" case. hrm.
				currentKey = ffj_t_Solr4Vufind13v1no_such_key
				state = fflib.FFParse_want_colon
				goto mainparse
			} else {
				switch kn[0] {

				case 'a':

					if bytes.Equal(ffj_key_Solr4Vufind13v1_AccessFacet, kn) {
						currentKey = ffj_t_Solr4Vufind13v1_AccessFacet
						state = fflib.FFParse_want_colon
						goto mainparse

					} else if bytes.Equal(ffj_key_Solr4Vufind13v1_AuthorFacet, kn) {
						currentKey = ffj_t_Solr4Vufind13v1_AuthorFacet
						state = fflib.FFParse_want_colon
						goto mainparse

					} else if bytes.Equal(ffj_key_Solr4Vufind13v1_Allfields, kn) {
						currentKey = ffj_t_Solr4Vufind13v1_Allfields
						state = fflib.FFParse_want_colon
						goto mainparse

					} else if bytes.Equal(ffj_key_Solr4Vufind13v1_Author, kn) {
						currentKey = ffj_t_Solr4Vufind13v1_Author
						state = fflib.FFParse_want_colon
						goto mainparse

					} else if bytes.Equal(ffj_key_Solr4Vufind13v1_SecondaryAuthors, kn) {
						currentKey = ffj_t_Solr4Vufind13v1_SecondaryAuthors
						state = fflib.FFParse_want_colon
						goto mainparse
					}

				case 'f':

					if bytes.Equal(ffj_key_Solr4Vufind13v1_FormatDe15, kn) {
						currentKey = ffj_t_Solr4Vufind13v1_FormatDe15
						state = fflib.FFParse_want_colon
						goto mainparse

					} else if bytes.Equal(ffj_key_Solr4Vufind13v1_FincClassFacet, kn) {
						currentKey = ffj_t_Solr4Vufind13v1_FincClassFacet
						state = fflib.FFParse_want_colon
						goto mainparse

					} else if bytes.Equal(ffj_key_Solr4Vufind13v1_Formats, kn) {
						currentKey = ffj_t_Solr4Vufind13v1_Formats
						state = fflib.FFParse_want_colon
						goto mainparse

					} else if bytes.Equal(ffj_key_Solr4Vufind13v1_Fullrecord, kn) {
						currentKey = ffj_t_Solr4Vufind13v1_Fullrecord
						state = fflib.FFParse_want_colon
						goto mainparse

					} else if bytes.Equal(ffj_key_Solr4Vufind13v1_Fulltext, kn) {
						currentKey = ffj_t_Solr4Vufind13v1_Fulltext
						state = fflib.FFParse_want_colon
						goto mainparse
					}

				case 'h':

					if bytes.Equal(ffj_key_Solr4Vufind13v1_HierarchyParentTitle, kn) {
						currentKey = ffj_t_Solr4Vufind13v1_HierarchyParentTitle
						state = fflib.FFParse_want_colon
						goto mainparse
					}

				case 'i':

					if bytes.Equal(ffj_key_Solr4Vufind13v1_ID, kn) {
						currentKey = ffj_t_Solr4Vufind13v1_ID
						state = fflib.FFParse_want_colon
						goto mainparse

					} else if bytes.Equal(ffj_key_Solr4Vufind13v1_Institutions, kn) {
						currentKey = ffj_t_Solr4Vufind13v1_Institutions
						state = fflib.FFParse_want_colon
						goto mainparse

					} else if bytes.Equal(ffj_key_Solr4Vufind13v1_Imprint, kn) {
						currentKey = ffj_t_Solr4Vufind13v1_Imprint
						state = fflib.FFParse_want_colon
						goto mainparse

					} else if bytes.Equal(ffj_key_Solr4Vufind13v1_ISSN, kn) {
						currentKey = ffj_t_Solr4Vufind13v1_ISSN
						state = fflib.FFParse_want_colon
						goto mainparse
					}

				case 'l':

					if bytes.Equal(ffj_key_Solr4Vufind13v1_Languages, kn) {
						currentKey = ffj_t_Solr4Vufind13v1_Languages
						state = fflib.FFParse_want_colon
						goto mainparse
					}

				case 'm':

					if bytes.Equal(ffj_key_Solr4Vufind13v1_MegaCollections, kn) {
						currentKey = ffj_t_Solr4Vufind13v1_MegaCollections
						state = fflib.FFParse_want_colon
						goto mainparse
					}

				case 'p':

					if bytes.Equal(ffj_key_Solr4Vufind13v1_PublishDateSort, kn) {
						currentKey = ffj_t_Solr4Vufind13v1_PublishDateSort
						state = fflib.FFParse_want_colon
						goto mainparse

					} else if bytes.Equal(ffj_key_Solr4Vufind13v1_Publishers, kn) {
						currentKey = ffj_t_Solr4Vufind13v1_Publishers
						state = fflib.FFParse_want_colon
						goto mainparse
					}

				case 'r':

					if bytes.Equal(ffj_key_Solr4Vufind13v1_RecordType, kn) {
						currentKey = ffj_t_Solr4Vufind13v1_RecordType
						state = fflib.FFParse_want_colon
						goto mainparse
					}

				case 's':

					if bytes.Equal(ffj_key_Solr4Vufind13v1_Series, kn) {
						currentKey = ffj_t_Solr4Vufind13v1_Series
						state = fflib.FFParse_want_colon
						goto mainparse

					} else if bytes.Equal(ffj_key_Solr4Vufind13v1_SourceID, kn) {
						currentKey = ffj_t_Solr4Vufind13v1_SourceID
						state = fflib.FFParse_want_colon
						goto mainparse
					}

				case 't':

					if bytes.Equal(ffj_key_Solr4Vufind13v1_Subtitle, kn) {
						currentKey = ffj_t_Solr4Vufind13v1_Subtitle
						state = fflib.FFParse_want_colon
						goto mainparse

					} else if bytes.Equal(ffj_key_Solr4Vufind13v1_Title, kn) {
						currentKey = ffj_t_Solr4Vufind13v1_Title
						state = fflib.FFParse_want_colon
						goto mainparse

					} else if bytes.Equal(ffj_key_Solr4Vufind13v1_TitleFull, kn) {
						currentKey = ffj_t_Solr4Vufind13v1_TitleFull
						state = fflib.FFParse_want_colon
						goto mainparse

					} else if bytes.Equal(ffj_key_Solr4Vufind13v1_TitleShort, kn) {
						currentKey = ffj_t_Solr4Vufind13v1_TitleShort
						state = fflib.FFParse_want_colon
						goto mainparse

					} else if bytes.Equal(ffj_key_Solr4Vufind13v1_TitleSort, kn) {
						currentKey = ffj_t_Solr4Vufind13v1_TitleSort
						state = fflib.FFParse_want_colon
						goto mainparse

					} else if bytes.Equal(ffj_key_Solr4Vufind13v1_Topics, kn) {
						currentKey = ffj_t_Solr4Vufind13v1_Topics
						state = fflib.FFParse_want_colon
						goto mainparse
					}

				case 'u':

					if bytes.Equal(ffj_key_Solr4Vufind13v1_URL, kn) {
						currentKey = ffj_t_Solr4Vufind13v1_URL
						state = fflib.FFParse_want_colon
						goto mainparse
					}

				}

				if fflib.SimpleLetterEqualFold(ffj_key_Solr4Vufind13v1_URL, kn) {
					currentKey = ffj_t_Solr4Vufind13v1_URL
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				if fflib.SimpleLetterEqualFold(ffj_key_Solr4Vufind13v1_Topics, kn) {
					currentKey = ffj_t_Solr4Vufind13v1_Topics
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				if fflib.EqualFoldRight(ffj_key_Solr4Vufind13v1_TitleSort, kn) {
					currentKey = ffj_t_Solr4Vufind13v1_TitleSort
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				if fflib.EqualFoldRight(ffj_key_Solr4Vufind13v1_TitleShort, kn) {
					currentKey = ffj_t_Solr4Vufind13v1_TitleShort
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				if fflib.AsciiEqualFold(ffj_key_Solr4Vufind13v1_TitleFull, kn) {
					currentKey = ffj_t_Solr4Vufind13v1_TitleFull
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				if fflib.SimpleLetterEqualFold(ffj_key_Solr4Vufind13v1_Title, kn) {
					currentKey = ffj_t_Solr4Vufind13v1_Title
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				if fflib.EqualFoldRight(ffj_key_Solr4Vufind13v1_Subtitle, kn) {
					currentKey = ffj_t_Solr4Vufind13v1_Subtitle
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				if fflib.EqualFoldRight(ffj_key_Solr4Vufind13v1_SourceID, kn) {
					currentKey = ffj_t_Solr4Vufind13v1_SourceID
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				if fflib.AsciiEqualFold(ffj_key_Solr4Vufind13v1_SecondaryAuthors, kn) {
					currentKey = ffj_t_Solr4Vufind13v1_SecondaryAuthors
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				if fflib.EqualFoldRight(ffj_key_Solr4Vufind13v1_Series, kn) {
					currentKey = ffj_t_Solr4Vufind13v1_Series
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				if fflib.SimpleLetterEqualFold(ffj_key_Solr4Vufind13v1_RecordType, kn) {
					currentKey = ffj_t_Solr4Vufind13v1_RecordType
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				if fflib.EqualFoldRight(ffj_key_Solr4Vufind13v1_Publishers, kn) {
					currentKey = ffj_t_Solr4Vufind13v1_Publishers
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				if fflib.EqualFoldRight(ffj_key_Solr4Vufind13v1_PublishDateSort, kn) {
					currentKey = ffj_t_Solr4Vufind13v1_PublishDateSort
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				if fflib.AsciiEqualFold(ffj_key_Solr4Vufind13v1_MegaCollections, kn) {
					currentKey = ffj_t_Solr4Vufind13v1_MegaCollections
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				if fflib.SimpleLetterEqualFold(ffj_key_Solr4Vufind13v1_Languages, kn) {
					currentKey = ffj_t_Solr4Vufind13v1_Languages
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				if fflib.EqualFoldRight(ffj_key_Solr4Vufind13v1_ISSN, kn) {
					currentKey = ffj_t_Solr4Vufind13v1_ISSN
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				if fflib.SimpleLetterEqualFold(ffj_key_Solr4Vufind13v1_Imprint, kn) {
					currentKey = ffj_t_Solr4Vufind13v1_Imprint
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				if fflib.EqualFoldRight(ffj_key_Solr4Vufind13v1_Institutions, kn) {
					currentKey = ffj_t_Solr4Vufind13v1_Institutions
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				if fflib.SimpleLetterEqualFold(ffj_key_Solr4Vufind13v1_ID, kn) {
					currentKey = ffj_t_Solr4Vufind13v1_ID
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				if fflib.AsciiEqualFold(ffj_key_Solr4Vufind13v1_HierarchyParentTitle, kn) {
					currentKey = ffj_t_Solr4Vufind13v1_HierarchyParentTitle
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				if fflib.SimpleLetterEqualFold(ffj_key_Solr4Vufind13v1_Fulltext, kn) {
					currentKey = ffj_t_Solr4Vufind13v1_Fulltext
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				if fflib.SimpleLetterEqualFold(ffj_key_Solr4Vufind13v1_Fullrecord, kn) {
					currentKey = ffj_t_Solr4Vufind13v1_Fullrecord
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				if fflib.SimpleLetterEqualFold(ffj_key_Solr4Vufind13v1_Formats, kn) {
					currentKey = ffj_t_Solr4Vufind13v1_Formats
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				if fflib.EqualFoldRight(ffj_key_Solr4Vufind13v1_FincClassFacet, kn) {
					currentKey = ffj_t_Solr4Vufind13v1_FincClassFacet
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				if fflib.SimpleLetterEqualFold(ffj_key_Solr4Vufind13v1_Author, kn) {
					currentKey = ffj_t_Solr4Vufind13v1_Author
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				if fflib.EqualFoldRight(ffj_key_Solr4Vufind13v1_Allfields, kn) {
					currentKey = ffj_t_Solr4Vufind13v1_Allfields
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				if fflib.AsciiEqualFold(ffj_key_Solr4Vufind13v1_AuthorFacet, kn) {
					currentKey = ffj_t_Solr4Vufind13v1_AuthorFacet
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				if fflib.EqualFoldRight(ffj_key_Solr4Vufind13v1_AccessFacet, kn) {
					currentKey = ffj_t_Solr4Vufind13v1_AccessFacet
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				if fflib.AsciiEqualFold(ffj_key_Solr4Vufind13v1_FormatDe15, kn) {
					currentKey = ffj_t_Solr4Vufind13v1_FormatDe15
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				currentKey = ffj_t_Solr4Vufind13v1no_such_key
				state = fflib.FFParse_want_colon
				goto mainparse
			}

		case fflib.FFParse_want_colon:
			if tok != fflib.FFTok_colon {
				wantedTok = fflib.FFTok_colon
				goto wrongtokenerror
			}
			state = fflib.FFParse_want_value
			continue
		case fflib.FFParse_want_value:

			if tok == fflib.FFTok_left_brace || tok == fflib.FFTok_left_bracket || tok == fflib.FFTok_integer || tok == fflib.FFTok_double || tok == fflib.FFTok_string || tok == fflib.FFTok_bool || tok == fflib.FFTok_null {
				switch currentKey {

				case ffj_t_Solr4Vufind13v1_FormatDe15:
					goto handle_FormatDe15

				case ffj_t_Solr4Vufind13v1_AccessFacet:
					goto handle_AccessFacet

				case ffj_t_Solr4Vufind13v1_AuthorFacet:
					goto handle_AuthorFacet

				case ffj_t_Solr4Vufind13v1_Allfields:
					goto handle_Allfields

				case ffj_t_Solr4Vufind13v1_Author:
					goto handle_Author

				case ffj_t_Solr4Vufind13v1_FincClassFacet:
					goto handle_FincClassFacet

				case ffj_t_Solr4Vufind13v1_Formats:
					goto handle_Formats

				case ffj_t_Solr4Vufind13v1_Fullrecord:
					goto handle_Fullrecord

				case ffj_t_Solr4Vufind13v1_Fulltext:
					goto handle_Fulltext

				case ffj_t_Solr4Vufind13v1_HierarchyParentTitle:
					goto handle_HierarchyParentTitle

				case ffj_t_Solr4Vufind13v1_ID:
					goto handle_ID

				case ffj_t_Solr4Vufind13v1_Institutions:
					goto handle_Institutions

				case ffj_t_Solr4Vufind13v1_Imprint:
					goto handle_Imprint

				case ffj_t_Solr4Vufind13v1_ISSN:
					goto handle_ISSN

				case ffj_t_Solr4Vufind13v1_Languages:
					goto handle_Languages

				case ffj_t_Solr4Vufind13v1_MegaCollections:
					goto handle_MegaCollections

				case ffj_t_Solr4Vufind13v1_PublishDateSort:
					goto handle_PublishDateSort

				case ffj_t_Solr4Vufind13v1_Publishers:
					goto handle_Publishers

				case ffj_t_Solr4Vufind13v1_RecordType:
					goto handle_RecordType

				case ffj_t_Solr4Vufind13v1_Series:
					goto handle_Series

				case ffj_t_Solr4Vufind13v1_SecondaryAuthors:
					goto handle_SecondaryAuthors

				case ffj_t_Solr4Vufind13v1_SourceID:
					goto handle_SourceID

				case ffj_t_Solr4Vufind13v1_Subtitle:
					goto handle_Subtitle

				case ffj_t_Solr4Vufind13v1_Title:
					goto handle_Title

				case ffj_t_Solr4Vufind13v1_TitleFull:
					goto handle_TitleFull

				case ffj_t_Solr4Vufind13v1_TitleShort:
					goto handle_TitleShort

				case ffj_t_Solr4Vufind13v1_TitleSort:
					goto handle_TitleSort

				case ffj_t_Solr4Vufind13v1_Topics:
					goto handle_Topics

				case ffj_t_Solr4Vufind13v1_URL:
					goto handle_URL

				case ffj_t_Solr4Vufind13v1no_such_key:
					err = fs.SkipField(tok)
					if err != nil {
						return fs.WrapErr(err)
					}
					state = fflib.FFParse_after_value
					goto mainparse
				}
			} else {
				goto wantedvalue
			}
		}
	}

handle_FormatDe15:

	/* handler: uj.FormatDe15 type=[]string kind=slice quoted=false*/

	{

		{
			if tok != fflib.FFTok_left_brace && tok != fflib.FFTok_null {
				return fs.WrapErr(fmt.Errorf("cannot unmarshal %s into Go value for ", tok))
			}
		}

		if tok == fflib.FFTok_null {
			uj.FormatDe15 = nil
		} else {

			uj.FormatDe15 = make([]string, 0)

			wantVal := true

			for {

				var v string

				tok = fs.Scan()
				if tok == fflib.FFTok_error {
					goto tokerror
				}
				if tok == fflib.FFTok_right_brace {
					break
				}

				if tok == fflib.FFTok_comma {
					if wantVal == true {
						// TODO(pquerna): this isn't an ideal error message, this handles
						// things like [,,,] as an array value.
						return fs.WrapErr(fmt.Errorf("wanted value token, but got token: %v", tok))
					}
					continue
				} else {
					wantVal = true
				}

				/* handler: v type=string kind=string quoted=false*/

				{

					{
						if tok != fflib.FFTok_string && tok != fflib.FFTok_null {
							return fs.WrapErr(fmt.Errorf("cannot unmarshal %s into Go value for string", tok))
						}
					}

					if tok == fflib.FFTok_null {

					} else {

						outBuf := fs.Output.Bytes()

						v = string(string(outBuf))

					}
				}

				uj.FormatDe15 = append(uj.FormatDe15, v)
				wantVal = false
			}
		}
	}

	state = fflib.FFParse_after_value
	goto mainparse

handle_AccessFacet:

	/* handler: uj.AccessFacet type=string kind=string quoted=false*/

	{

		{
			if tok != fflib.FFTok_string && tok != fflib.FFTok_null {
				return fs.WrapErr(fmt.Errorf("cannot unmarshal %s into Go value for string", tok))
			}
		}

		if tok == fflib.FFTok_null {

		} else {

			outBuf := fs.Output.Bytes()

			uj.AccessFacet = string(string(outBuf))

		}
	}

	state = fflib.FFParse_after_value
	goto mainparse

handle_AuthorFacet:

	/* handler: uj.AuthorFacet type=[]string kind=slice quoted=false*/

	{

		{
			if tok != fflib.FFTok_left_brace && tok != fflib.FFTok_null {
				return fs.WrapErr(fmt.Errorf("cannot unmarshal %s into Go value for ", tok))
			}
		}

		if tok == fflib.FFTok_null {
			uj.AuthorFacet = nil
		} else {

			uj.AuthorFacet = make([]string, 0)

			wantVal := true

			for {

				var v string

				tok = fs.Scan()
				if tok == fflib.FFTok_error {
					goto tokerror
				}
				if tok == fflib.FFTok_right_brace {
					break
				}

				if tok == fflib.FFTok_comma {
					if wantVal == true {
						// TODO(pquerna): this isn't an ideal error message, this handles
						// things like [,,,] as an array value.
						return fs.WrapErr(fmt.Errorf("wanted value token, but got token: %v", tok))
					}
					continue
				} else {
					wantVal = true
				}

				/* handler: v type=string kind=string quoted=false*/

				{

					{
						if tok != fflib.FFTok_string && tok != fflib.FFTok_null {
							return fs.WrapErr(fmt.Errorf("cannot unmarshal %s into Go value for string", tok))
						}
					}

					if tok == fflib.FFTok_null {

					} else {

						outBuf := fs.Output.Bytes()

						v = string(string(outBuf))

					}
				}

				uj.AuthorFacet = append(uj.AuthorFacet, v)
				wantVal = false
			}
		}
	}

	state = fflib.FFParse_after_value
	goto mainparse

handle_Allfields:

	/* handler: uj.Allfields type=string kind=string quoted=false*/

	{

		{
			if tok != fflib.FFTok_string && tok != fflib.FFTok_null {
				return fs.WrapErr(fmt.Errorf("cannot unmarshal %s into Go value for string", tok))
			}
		}

		if tok == fflib.FFTok_null {

		} else {

			outBuf := fs.Output.Bytes()

			uj.Allfields = string(string(outBuf))

		}
	}

	state = fflib.FFParse_after_value
	goto mainparse

handle_Author:

	/* handler: uj.Author type=string kind=string quoted=false*/

	{

		{
			if tok != fflib.FFTok_string && tok != fflib.FFTok_null {
				return fs.WrapErr(fmt.Errorf("cannot unmarshal %s into Go value for string", tok))
			}
		}

		if tok == fflib.FFTok_null {

		} else {

			outBuf := fs.Output.Bytes()

			uj.Author = string(string(outBuf))

		}
	}

	state = fflib.FFParse_after_value
	goto mainparse

handle_FincClassFacet:

	/* handler: uj.FincClassFacet type=[]string kind=slice quoted=false*/

	{

		{
			if tok != fflib.FFTok_left_brace && tok != fflib.FFTok_null {
				return fs.WrapErr(fmt.Errorf("cannot unmarshal %s into Go value for ", tok))
			}
		}

		if tok == fflib.FFTok_null {
			uj.FincClassFacet = nil
		} else {

			uj.FincClassFacet = make([]string, 0)

			wantVal := true

			for {

				var v string

				tok = fs.Scan()
				if tok == fflib.FFTok_error {
					goto tokerror
				}
				if tok == fflib.FFTok_right_brace {
					break
				}

				if tok == fflib.FFTok_comma {
					if wantVal == true {
						// TODO(pquerna): this isn't an ideal error message, this handles
						// things like [,,,] as an array value.
						return fs.WrapErr(fmt.Errorf("wanted value token, but got token: %v", tok))
					}
					continue
				} else {
					wantVal = true
				}

				/* handler: v type=string kind=string quoted=false*/

				{

					{
						if tok != fflib.FFTok_string && tok != fflib.FFTok_null {
							return fs.WrapErr(fmt.Errorf("cannot unmarshal %s into Go value for string", tok))
						}
					}

					if tok == fflib.FFTok_null {

					} else {

						outBuf := fs.Output.Bytes()

						v = string(string(outBuf))

					}
				}

				uj.FincClassFacet = append(uj.FincClassFacet, v)
				wantVal = false
			}
		}
	}

	state = fflib.FFParse_after_value
	goto mainparse

handle_Formats:

	/* handler: uj.Formats type=[]string kind=slice quoted=false*/

	{

		{
			if tok != fflib.FFTok_left_brace && tok != fflib.FFTok_null {
				return fs.WrapErr(fmt.Errorf("cannot unmarshal %s into Go value for ", tok))
			}
		}

		if tok == fflib.FFTok_null {
			uj.Formats = nil
		} else {

			uj.Formats = make([]string, 0)

			wantVal := true

			for {

				var v string

				tok = fs.Scan()
				if tok == fflib.FFTok_error {
					goto tokerror
				}
				if tok == fflib.FFTok_right_brace {
					break
				}

				if tok == fflib.FFTok_comma {
					if wantVal == true {
						// TODO(pquerna): this isn't an ideal error message, this handles
						// things like [,,,] as an array value.
						return fs.WrapErr(fmt.Errorf("wanted value token, but got token: %v", tok))
					}
					continue
				} else {
					wantVal = true
				}

				/* handler: v type=string kind=string quoted=false*/

				{

					{
						if tok != fflib.FFTok_string && tok != fflib.FFTok_null {
							return fs.WrapErr(fmt.Errorf("cannot unmarshal %s into Go value for string", tok))
						}
					}

					if tok == fflib.FFTok_null {

					} else {

						outBuf := fs.Output.Bytes()

						v = string(string(outBuf))

					}
				}

				uj.Formats = append(uj.Formats, v)
				wantVal = false
			}
		}
	}

	state = fflib.FFParse_after_value
	goto mainparse

handle_Fullrecord:

	/* handler: uj.Fullrecord type=string kind=string quoted=false*/

	{

		{
			if tok != fflib.FFTok_string && tok != fflib.FFTok_null {
				return fs.WrapErr(fmt.Errorf("cannot unmarshal %s into Go value for string", tok))
			}
		}

		if tok == fflib.FFTok_null {

		} else {

			outBuf := fs.Output.Bytes()

			uj.Fullrecord = string(string(outBuf))

		}
	}

	state = fflib.FFParse_after_value
	goto mainparse

handle_Fulltext:

	/* handler: uj.Fulltext type=string kind=string quoted=false*/

	{

		{
			if tok != fflib.FFTok_string && tok != fflib.FFTok_null {
				return fs.WrapErr(fmt.Errorf("cannot unmarshal %s into Go value for string", tok))
			}
		}

		if tok == fflib.FFTok_null {

		} else {

			outBuf := fs.Output.Bytes()

			uj.Fulltext = string(string(outBuf))

		}
	}

	state = fflib.FFParse_after_value
	goto mainparse

handle_HierarchyParentTitle:

	/* handler: uj.HierarchyParentTitle type=[]string kind=slice quoted=false*/

	{

		{
			if tok != fflib.FFTok_left_brace && tok != fflib.FFTok_null {
				return fs.WrapErr(fmt.Errorf("cannot unmarshal %s into Go value for ", tok))
			}
		}

		if tok == fflib.FFTok_null {
			uj.HierarchyParentTitle = nil
		} else {

			uj.HierarchyParentTitle = make([]string, 0)

			wantVal := true

			for {

				var v string

				tok = fs.Scan()
				if tok == fflib.FFTok_error {
					goto tokerror
				}
				if tok == fflib.FFTok_right_brace {
					break
				}

				if tok == fflib.FFTok_comma {
					if wantVal == true {
						// TODO(pquerna): this isn't an ideal error message, this handles
						// things like [,,,] as an array value.
						return fs.WrapErr(fmt.Errorf("wanted value token, but got token: %v", tok))
					}
					continue
				} else {
					wantVal = true
				}

				/* handler: v type=string kind=string quoted=false*/

				{

					{
						if tok != fflib.FFTok_string && tok != fflib.FFTok_null {
							return fs.WrapErr(fmt.Errorf("cannot unmarshal %s into Go value for string", tok))
						}
					}

					if tok == fflib.FFTok_null {

					} else {

						outBuf := fs.Output.Bytes()

						v = string(string(outBuf))

					}
				}

				uj.HierarchyParentTitle = append(uj.HierarchyParentTitle, v)
				wantVal = false
			}
		}
	}

	state = fflib.FFParse_after_value
	goto mainparse

handle_ID:

	/* handler: uj.ID type=string kind=string quoted=false*/

	{

		{
			if tok != fflib.FFTok_string && tok != fflib.FFTok_null {
				return fs.WrapErr(fmt.Errorf("cannot unmarshal %s into Go value for string", tok))
			}
		}

		if tok == fflib.FFTok_null {

		} else {

			outBuf := fs.Output.Bytes()

			uj.ID = string(string(outBuf))

		}
	}

	state = fflib.FFParse_after_value
	goto mainparse

handle_Institutions:

	/* handler: uj.Institutions type=[]string kind=slice quoted=false*/

	{

		{
			if tok != fflib.FFTok_left_brace && tok != fflib.FFTok_null {
				return fs.WrapErr(fmt.Errorf("cannot unmarshal %s into Go value for ", tok))
			}
		}

		if tok == fflib.FFTok_null {
			uj.Institutions = nil
		} else {

			uj.Institutions = make([]string, 0)

			wantVal := true

			for {

				var v string

				tok = fs.Scan()
				if tok == fflib.FFTok_error {
					goto tokerror
				}
				if tok == fflib.FFTok_right_brace {
					break
				}

				if tok == fflib.FFTok_comma {
					if wantVal == true {
						// TODO(pquerna): this isn't an ideal error message, this handles
						// things like [,,,] as an array value.
						return fs.WrapErr(fmt.Errorf("wanted value token, but got token: %v", tok))
					}
					continue
				} else {
					wantVal = true
				}

				/* handler: v type=string kind=string quoted=false*/

				{

					{
						if tok != fflib.FFTok_string && tok != fflib.FFTok_null {
							return fs.WrapErr(fmt.Errorf("cannot unmarshal %s into Go value for string", tok))
						}
					}

					if tok == fflib.FFTok_null {

					} else {

						outBuf := fs.Output.Bytes()

						v = string(string(outBuf))

					}
				}

				uj.Institutions = append(uj.Institutions, v)
				wantVal = false
			}
		}
	}

	state = fflib.FFParse_after_value
	goto mainparse

handle_Imprint:

	/* handler: uj.Imprint type=string kind=string quoted=false*/

	{

		{
			if tok != fflib.FFTok_string && tok != fflib.FFTok_null {
				return fs.WrapErr(fmt.Errorf("cannot unmarshal %s into Go value for string", tok))
			}
		}

		if tok == fflib.FFTok_null {

		} else {

			outBuf := fs.Output.Bytes()

			uj.Imprint = string(string(outBuf))

		}
	}

	state = fflib.FFParse_after_value
	goto mainparse

handle_ISSN:

	/* handler: uj.ISSN type=[]string kind=slice quoted=false*/

	{

		{
			if tok != fflib.FFTok_left_brace && tok != fflib.FFTok_null {
				return fs.WrapErr(fmt.Errorf("cannot unmarshal %s into Go value for ", tok))
			}
		}

		if tok == fflib.FFTok_null {
			uj.ISSN = nil
		} else {

			uj.ISSN = make([]string, 0)

			wantVal := true

			for {

				var v string

				tok = fs.Scan()
				if tok == fflib.FFTok_error {
					goto tokerror
				}
				if tok == fflib.FFTok_right_brace {
					break
				}

				if tok == fflib.FFTok_comma {
					if wantVal == true {
						// TODO(pquerna): this isn't an ideal error message, this handles
						// things like [,,,] as an array value.
						return fs.WrapErr(fmt.Errorf("wanted value token, but got token: %v", tok))
					}
					continue
				} else {
					wantVal = true
				}

				/* handler: v type=string kind=string quoted=false*/

				{

					{
						if tok != fflib.FFTok_string && tok != fflib.FFTok_null {
							return fs.WrapErr(fmt.Errorf("cannot unmarshal %s into Go value for string", tok))
						}
					}

					if tok == fflib.FFTok_null {

					} else {

						outBuf := fs.Output.Bytes()

						v = string(string(outBuf))

					}
				}

				uj.ISSN = append(uj.ISSN, v)
				wantVal = false
			}
		}
	}

	state = fflib.FFParse_after_value
	goto mainparse

handle_Languages:

	/* handler: uj.Languages type=[]string kind=slice quoted=false*/

	{

		{
			if tok != fflib.FFTok_left_brace && tok != fflib.FFTok_null {
				return fs.WrapErr(fmt.Errorf("cannot unmarshal %s into Go value for ", tok))
			}
		}

		if tok == fflib.FFTok_null {
			uj.Languages = nil
		} else {

			uj.Languages = make([]string, 0)

			wantVal := true

			for {

				var v string

				tok = fs.Scan()
				if tok == fflib.FFTok_error {
					goto tokerror
				}
				if tok == fflib.FFTok_right_brace {
					break
				}

				if tok == fflib.FFTok_comma {
					if wantVal == true {
						// TODO(pquerna): this isn't an ideal error message, this handles
						// things like [,,,] as an array value.
						return fs.WrapErr(fmt.Errorf("wanted value token, but got token: %v", tok))
					}
					continue
				} else {
					wantVal = true
				}

				/* handler: v type=string kind=string quoted=false*/

				{

					{
						if tok != fflib.FFTok_string && tok != fflib.FFTok_null {
							return fs.WrapErr(fmt.Errorf("cannot unmarshal %s into Go value for string", tok))
						}
					}

					if tok == fflib.FFTok_null {

					} else {

						outBuf := fs.Output.Bytes()

						v = string(string(outBuf))

					}
				}

				uj.Languages = append(uj.Languages, v)
				wantVal = false
			}
		}
	}

	state = fflib.FFParse_after_value
	goto mainparse

handle_MegaCollections:

	/* handler: uj.MegaCollections type=[]string kind=slice quoted=false*/

	{

		{
			if tok != fflib.FFTok_left_brace && tok != fflib.FFTok_null {
				return fs.WrapErr(fmt.Errorf("cannot unmarshal %s into Go value for ", tok))
			}
		}

		if tok == fflib.FFTok_null {
			uj.MegaCollections = nil
		} else {

			uj.MegaCollections = make([]string, 0)

			wantVal := true

			for {

				var v string

				tok = fs.Scan()
				if tok == fflib.FFTok_error {
					goto tokerror
				}
				if tok == fflib.FFTok_right_brace {
					break
				}

				if tok == fflib.FFTok_comma {
					if wantVal == true {
						// TODO(pquerna): this isn't an ideal error message, this handles
						// things like [,,,] as an array value.
						return fs.WrapErr(fmt.Errorf("wanted value token, but got token: %v", tok))
					}
					continue
				} else {
					wantVal = true
				}

				/* handler: v type=string kind=string quoted=false*/

				{

					{
						if tok != fflib.FFTok_string && tok != fflib.FFTok_null {
							return fs.WrapErr(fmt.Errorf("cannot unmarshal %s into Go value for string", tok))
						}
					}

					if tok == fflib.FFTok_null {

					} else {

						outBuf := fs.Output.Bytes()

						v = string(string(outBuf))

					}
				}

				uj.MegaCollections = append(uj.MegaCollections, v)
				wantVal = false
			}
		}
	}

	state = fflib.FFParse_after_value
	goto mainparse

handle_PublishDateSort:

	/* handler: uj.PublishDateSort type=int kind=int quoted=false*/

	{
		if tok != fflib.FFTok_integer && tok != fflib.FFTok_null {
			return fs.WrapErr(fmt.Errorf("cannot unmarshal %s into Go value for int", tok))
		}
	}

	{

		if tok == fflib.FFTok_null {

		} else {

			tval, err := fflib.ParseInt(fs.Output.Bytes(), 10, 64)

			if err != nil {
				return fs.WrapErr(err)
			}

			uj.PublishDateSort = int(tval)

		}
	}

	state = fflib.FFParse_after_value
	goto mainparse

handle_Publishers:

	/* handler: uj.Publishers type=[]string kind=slice quoted=false*/

	{

		{
			if tok != fflib.FFTok_left_brace && tok != fflib.FFTok_null {
				return fs.WrapErr(fmt.Errorf("cannot unmarshal %s into Go value for ", tok))
			}
		}

		if tok == fflib.FFTok_null {
			uj.Publishers = nil
		} else {

			uj.Publishers = make([]string, 0)

			wantVal := true

			for {

				var v string

				tok = fs.Scan()
				if tok == fflib.FFTok_error {
					goto tokerror
				}
				if tok == fflib.FFTok_right_brace {
					break
				}

				if tok == fflib.FFTok_comma {
					if wantVal == true {
						// TODO(pquerna): this isn't an ideal error message, this handles
						// things like [,,,] as an array value.
						return fs.WrapErr(fmt.Errorf("wanted value token, but got token: %v", tok))
					}
					continue
				} else {
					wantVal = true
				}

				/* handler: v type=string kind=string quoted=false*/

				{

					{
						if tok != fflib.FFTok_string && tok != fflib.FFTok_null {
							return fs.WrapErr(fmt.Errorf("cannot unmarshal %s into Go value for string", tok))
						}
					}

					if tok == fflib.FFTok_null {

					} else {

						outBuf := fs.Output.Bytes()

						v = string(string(outBuf))

					}
				}

				uj.Publishers = append(uj.Publishers, v)
				wantVal = false
			}
		}
	}

	state = fflib.FFParse_after_value
	goto mainparse

handle_RecordType:

	/* handler: uj.RecordType type=string kind=string quoted=false*/

	{

		{
			if tok != fflib.FFTok_string && tok != fflib.FFTok_null {
				return fs.WrapErr(fmt.Errorf("cannot unmarshal %s into Go value for string", tok))
			}
		}

		if tok == fflib.FFTok_null {

		} else {

			outBuf := fs.Output.Bytes()

			uj.RecordType = string(string(outBuf))

		}
	}

	state = fflib.FFParse_after_value
	goto mainparse

handle_Series:

	/* handler: uj.Series type=[]string kind=slice quoted=false*/

	{

		{
			if tok != fflib.FFTok_left_brace && tok != fflib.FFTok_null {
				return fs.WrapErr(fmt.Errorf("cannot unmarshal %s into Go value for ", tok))
			}
		}

		if tok == fflib.FFTok_null {
			uj.Series = nil
		} else {

			uj.Series = make([]string, 0)

			wantVal := true

			for {

				var v string

				tok = fs.Scan()
				if tok == fflib.FFTok_error {
					goto tokerror
				}
				if tok == fflib.FFTok_right_brace {
					break
				}

				if tok == fflib.FFTok_comma {
					if wantVal == true {
						// TODO(pquerna): this isn't an ideal error message, this handles
						// things like [,,,] as an array value.
						return fs.WrapErr(fmt.Errorf("wanted value token, but got token: %v", tok))
					}
					continue
				} else {
					wantVal = true
				}

				/* handler: v type=string kind=string quoted=false*/

				{

					{
						if tok != fflib.FFTok_string && tok != fflib.FFTok_null {
							return fs.WrapErr(fmt.Errorf("cannot unmarshal %s into Go value for string", tok))
						}
					}

					if tok == fflib.FFTok_null {

					} else {

						outBuf := fs.Output.Bytes()

						v = string(string(outBuf))

					}
				}

				uj.Series = append(uj.Series, v)
				wantVal = false
			}
		}
	}

	state = fflib.FFParse_after_value
	goto mainparse

handle_SecondaryAuthors:

	/* handler: uj.SecondaryAuthors type=[]string kind=slice quoted=false*/

	{

		{
			if tok != fflib.FFTok_left_brace && tok != fflib.FFTok_null {
				return fs.WrapErr(fmt.Errorf("cannot unmarshal %s into Go value for ", tok))
			}
		}

		if tok == fflib.FFTok_null {
			uj.SecondaryAuthors = nil
		} else {

			uj.SecondaryAuthors = make([]string, 0)

			wantVal := true

			for {

				var v string

				tok = fs.Scan()
				if tok == fflib.FFTok_error {
					goto tokerror
				}
				if tok == fflib.FFTok_right_brace {
					break
				}

				if tok == fflib.FFTok_comma {
					if wantVal == true {
						// TODO(pquerna): this isn't an ideal error message, this handles
						// things like [,,,] as an array value.
						return fs.WrapErr(fmt.Errorf("wanted value token, but got token: %v", tok))
					}
					continue
				} else {
					wantVal = true
				}

				/* handler: v type=string kind=string quoted=false*/

				{

					{
						if tok != fflib.FFTok_string && tok != fflib.FFTok_null {
							return fs.WrapErr(fmt.Errorf("cannot unmarshal %s into Go value for string", tok))
						}
					}

					if tok == fflib.FFTok_null {

					} else {

						outBuf := fs.Output.Bytes()

						v = string(string(outBuf))

					}
				}

				uj.SecondaryAuthors = append(uj.SecondaryAuthors, v)
				wantVal = false
			}
		}
	}

	state = fflib.FFParse_after_value
	goto mainparse

handle_SourceID:

	/* handler: uj.SourceID type=string kind=string quoted=false*/

	{

		{
			if tok != fflib.FFTok_string && tok != fflib.FFTok_null {
				return fs.WrapErr(fmt.Errorf("cannot unmarshal %s into Go value for string", tok))
			}
		}

		if tok == fflib.FFTok_null {

		} else {

			outBuf := fs.Output.Bytes()

			uj.SourceID = string(string(outBuf))

		}
	}

	state = fflib.FFParse_after_value
	goto mainparse

handle_Subtitle:

	/* handler: uj.Subtitle type=string kind=string quoted=false*/

	{

		{
			if tok != fflib.FFTok_string && tok != fflib.FFTok_null {
				return fs.WrapErr(fmt.Errorf("cannot unmarshal %s into Go value for string", tok))
			}
		}

		if tok == fflib.FFTok_null {

		} else {

			outBuf := fs.Output.Bytes()

			uj.Subtitle = string(string(outBuf))

		}
	}

	state = fflib.FFParse_after_value
	goto mainparse

handle_Title:

	/* handler: uj.Title type=string kind=string quoted=false*/

	{

		{
			if tok != fflib.FFTok_string && tok != fflib.FFTok_null {
				return fs.WrapErr(fmt.Errorf("cannot unmarshal %s into Go value for string", tok))
			}
		}

		if tok == fflib.FFTok_null {

		} else {

			outBuf := fs.Output.Bytes()

			uj.Title = string(string(outBuf))

		}
	}

	state = fflib.FFParse_after_value
	goto mainparse

handle_TitleFull:

	/* handler: uj.TitleFull type=string kind=string quoted=false*/

	{

		{
			if tok != fflib.FFTok_string && tok != fflib.FFTok_null {
				return fs.WrapErr(fmt.Errorf("cannot unmarshal %s into Go value for string", tok))
			}
		}

		if tok == fflib.FFTok_null {

		} else {

			outBuf := fs.Output.Bytes()

			uj.TitleFull = string(string(outBuf))

		}
	}

	state = fflib.FFParse_after_value
	goto mainparse

handle_TitleShort:

	/* handler: uj.TitleShort type=string kind=string quoted=false*/

	{

		{
			if tok != fflib.FFTok_string && tok != fflib.FFTok_null {
				return fs.WrapErr(fmt.Errorf("cannot unmarshal %s into Go value for string", tok))
			}
		}

		if tok == fflib.FFTok_null {

		} else {

			outBuf := fs.Output.Bytes()

			uj.TitleShort = string(string(outBuf))

		}
	}

	state = fflib.FFParse_after_value
	goto mainparse

handle_TitleSort:

	/* handler: uj.TitleSort type=string kind=string quoted=false*/

	{

		{
			if tok != fflib.FFTok_string && tok != fflib.FFTok_null {
				return fs.WrapErr(fmt.Errorf("cannot unmarshal %s into Go value for string", tok))
			}
		}

		if tok == fflib.FFTok_null {

		} else {

			outBuf := fs.Output.Bytes()

			uj.TitleSort = string(string(outBuf))

		}
	}

	state = fflib.FFParse_after_value
	goto mainparse

handle_Topics:

	/* handler: uj.Topics type=[]string kind=slice quoted=false*/

	{

		{
			if tok != fflib.FFTok_left_brace && tok != fflib.FFTok_null {
				return fs.WrapErr(fmt.Errorf("cannot unmarshal %s into Go value for ", tok))
			}
		}

		if tok == fflib.FFTok_null {
			uj.Topics = nil
		} else {

			uj.Topics = make([]string, 0)

			wantVal := true

			for {

				var v string

				tok = fs.Scan()
				if tok == fflib.FFTok_error {
					goto tokerror
				}
				if tok == fflib.FFTok_right_brace {
					break
				}

				if tok == fflib.FFTok_comma {
					if wantVal == true {
						// TODO(pquerna): this isn't an ideal error message, this handles
						// things like [,,,] as an array value.
						return fs.WrapErr(fmt.Errorf("wanted value token, but got token: %v", tok))
					}
					continue
				} else {
					wantVal = true
				}

				/* handler: v type=string kind=string quoted=false*/

				{

					{
						if tok != fflib.FFTok_string && tok != fflib.FFTok_null {
							return fs.WrapErr(fmt.Errorf("cannot unmarshal %s into Go value for string", tok))
						}
					}

					if tok == fflib.FFTok_null {

					} else {

						outBuf := fs.Output.Bytes()

						v = string(string(outBuf))

					}
				}

				uj.Topics = append(uj.Topics, v)
				wantVal = false
			}
		}
	}

	state = fflib.FFParse_after_value
	goto mainparse

handle_URL:

	/* handler: uj.URL type=[]string kind=slice quoted=false*/

	{

		{
			if tok != fflib.FFTok_left_brace && tok != fflib.FFTok_null {
				return fs.WrapErr(fmt.Errorf("cannot unmarshal %s into Go value for ", tok))
			}
		}

		if tok == fflib.FFTok_null {
			uj.URL = nil
		} else {

			uj.URL = make([]string, 0)

			wantVal := true

			for {

				var v string

				tok = fs.Scan()
				if tok == fflib.FFTok_error {
					goto tokerror
				}
				if tok == fflib.FFTok_right_brace {
					break
				}

				if tok == fflib.FFTok_comma {
					if wantVal == true {
						// TODO(pquerna): this isn't an ideal error message, this handles
						// things like [,,,] as an array value.
						return fs.WrapErr(fmt.Errorf("wanted value token, but got token: %v", tok))
					}
					continue
				} else {
					wantVal = true
				}

				/* handler: v type=string kind=string quoted=false*/

				{

					{
						if tok != fflib.FFTok_string && tok != fflib.FFTok_null {
							return fs.WrapErr(fmt.Errorf("cannot unmarshal %s into Go value for string", tok))
						}
					}

					if tok == fflib.FFTok_null {

					} else {

						outBuf := fs.Output.Bytes()

						v = string(string(outBuf))

					}
				}

				uj.URL = append(uj.URL, v)
				wantVal = false
			}
		}
	}

	state = fflib.FFParse_after_value
	goto mainparse

wantedvalue:
	return fs.WrapErr(fmt.Errorf("wanted value token, but got token: %v", tok))
wrongtokenerror:
	return fs.WrapErr(fmt.Errorf("ffjson: wanted token: %v, but got token: %v output=%s", wantedTok, tok, fs.Output.String()))
tokerror:
	if fs.BigError != nil {
		return fs.WrapErr(fs.BigError)
	}
	err = fs.Error.ToError()
	if err != nil {
		return fs.WrapErr(err)
	}
	panic("ffjson-generated: unreachable, please report bug.")
done:
	return nil
}
