graph TD

A[Edit GitLab] --> B[Trigger, span-webhookd]
B --> C[Clone or update local repo, git]
C --> D[Check if review.yaml has changed]
D --> E[If changed, start review, span-review -c review.yaml]
E --> F[If solr is set to auto, query whatislive nginx snippet for current testing solr]
F --> G[Format results as textile]
G --> H[Update ticket, span-review]

