.TH SPAN 1 "JULY 2016" "Leipzig University Library" "Manuals"
.SH NAME
.PP
span\-import, span\-tag, span\-export, span\-oa\-filter,
span\-update\-labels, span\-crossref\-snapshot, span\-local\-data, span\-freeze,
span\-amsl\-discovery \- intermediate
schema and integration tools
.SH SYNOPSIS
.PP
\fB\fCspan\-import\fR [\fB\fC\-i\fR \fIinput\-format\fP] < \fIfile\fP
.PP
\fB\fCspan\-tag\fR [\fB\fC\-c\fR \fIconfig\fP, \fB\fC\-unfreeze\fR \fIfile\fP, \fB\fC\-server\fR \fIurl\fP, \fB\fC\-prefs\fR \fIprefs\fP] < \fIfile\fP
.PP
\fB\fCspan\-tagger\fR [\fB\fC\-db\fR \fIfile\fP, \fB\fC\-f\fR, \fB\fC\-v\fR, \fB\fC\-debug\fR] < \fIfile\fP
.PP
\fB\fCspan\-export\fR [\fB\fC\-o\fR \fIoutput\-format\fP] < \fIfile\fP
.PP
\fB\fCspan\-oa\-filter\fR [\fB\fC\-f\fR \fIfile\fP] [\fB\fC\-fc\fR \fIfile\fP] [\fB\fC\-xsid\fR \fIstring\fP] [\fB\fC\-oasid\fR \fIstring\fP] < \fIfile\fP
.PP
\fB\fCspan\-update\-labels\fR [\fB\fC\-f\fR \fIfile\fP, \fB\fC\-s\fR \fIseparator\fP] < \fIfile\fP
.PP
\fB\fCspan\-crossref\-snapshot\fR [\fB\fC\-x\fR \fIfile\fP] [\fB\fC\-S\fR \fISIZE\fP] \-o \fIfile\fP \fIfile\fP
.PP
\fB\fCspan\-local\-data\fR < \fIfile\fP
.PP
\fB\fCspan\-freeze\fR \-o \fIfile\fP < \fIfile\fP
.PP
\fB\fCspan\-amsl\-discovery\fR \fB\fC\-live\fR \fIURL\fP [\fB\fC\-allow\-empty\fR] [\fB\fC\-verbose\fR]
.PP
\fB\fCspan\-crossref\-members\fR [\fB\fC\-base\fR \fIURL\fP] [\fB\fC\-offset\fR \fIN\fP] [\fB\fC\-rows\fR \fIN\fP] [\fB\fC\-q\fR] [\fB\fC\-sleep\fR \fIduration\fP]
.PP
\fB\fCspan\-crossref\-sync\fR [\fB\fC\-P\fR \fIprefix\fP] [\fB\fC\-i\fR *interval] [\fB\fC\-p\fR \fIcompress\-program\fP] [\fB\fC\-s\fR \fIdate\fP] [\fB\fC\-e\fR \fIdate\fP] [\fB\fC\-E\fR \fInumerrors\fP]
.SH DESCRIPTION
.PP
The \fB\fCspan\fR tools convert to and from an intermediate schema and support
license tagging and quality assurance.
.PP
The intermediate schema is a normalization vehicle, spec:
\[la]https://github.com/ubleipzig/intermediateschema\[ra]
.SH OPTIONS
.PP
This section is correct, but incomplete. Consult \fB\fC\-h\fR for further flags.
.TP
\fB\fC\-i\fR \fIformat\fP
Input format. \fB\fCspan\-import\fR only.
.TP
\fB\fC\-o\fR \fIformat\fP
Output format or file. \fB\fCspan\-export\fR, \fB\fCspan\-freeze\fR, \fB\fCspan\-crossref\-snapshot\fR only.
.TP
\fB\fC\-c\fR \fIconfig\-string\fP or \fIconfig\-file\fP
Configuration string or path to configuration file. \fB\fCspan\-tag\fR example in
EXAMPLE for a CONFIGURATION FILE.
.TP
\fB\fC\-list\fR
List supported formats. \fB\fCspan\-import\fR, \fB\fCspan\-export\fR only.
.TP
\fB\fC\-verbose\fR
More output. \fB\fCspan\-import\fR only.
.TP
\fB\fC\-b\fR \fIN\fP
Batch size. \fB\fCspan\-tag\fR, \fB\fCspan\-import\fR, \fB\fCspan\-export\fR, \fB\fCspan\-crossref\-snapshot\fR only.
.TP
\fB\fC\-w\fR \fIN\fP
Number of workers (defaults to CPU count). \fB\fCspan\-tag\fR, \fB\fCspan\-export\fR only.
.TP
\fB\fC\-cpuprofile\fR \fIpprof\-file\fP
Profiling. \fB\fCspan\-import\fR, \fB\fCspan\-tag\fR, \fB\fCspan\-crossref\-snapshot\fR only.
.TP
\fB\fC\-memprofile\fR \fIpprof\-file\fP
Profiling. \fB\fCspan\-import\fR, \fB\fCspan\-tag\fR, \fB\fCspan\-export\fR only.
.TP
\fB\fC\-f\fR \fIfile\fP
File location (ISSN list or ID,ISIL). \fB\fCspan\-oa\-filter\fR, \fB\fCspan\-update\-labels\fR only.
.TP
\fB\fC\-f\fR
Flatten output to table. \fB\fCspan\-amsl\-discovery\fR only.
.TP
\fB\fC\-fc\fR \fIfile\fP
File in AMSL FreeContent API format about sources, collections and their OA status, \fB\fCspan\-oa\-filter\fR only.
.TP
\fB\fC\-s\fR \fIsep\fP
Field separator. \fB\fCspan\-update\-labels\fR only.
.TP
\fB\fC\-unfreeze\fR \fIfile\fP
Take a file created with \fB\fCspan\-freeze\fR and use it instead of a filterconfig. \fB\fCspan\-tag\fR only.
.TP
\fB\fC\-v\fR or \fB\fC\-version\fR
Show version.
.TP
\fB\fC\-x\fR \fIfile\fP
Filename to DOI to exclude, one per line. \fB\fCspan\-crossref\-snapshot\fR only.
.TP
\fB\fC\-xsid\fR \fIsid\fP
Do not apply processing on a given source id. \fB\fCspan\-oa\-filter\fR only.
.TP
\fB\fC\-oasid\fR \fIsid\fP
Set \fB\fCx.oa\fR to true for all records of a given source id. \fB\fCspan\-oa\-filter\fR only.
.TP
\fB\fC\-z\fR
Input is gzip compressed. \fB\fCspan\-crossref\-snapshot\fR only.
.TP
\fB\fC\-logfile\fR \fIfile\fP
Logfile to log to. \fB\fCspan\-import\fR only.
.TP
\fB\fC\-base\fR \fIurl\fP
API base URL (default "\[la]http://api.crossref.org/members"\[ra]), \fB\fCspan\-crossref\-members\fR only.
.TP
\fB\fC\-offset\fR \fIN\fP
Offset to start fetching data from (default 0), \fB\fCspan\-crossref\-members\fR only.
.TP
\fB\fC\-rows\fR \fIN\fP
Rows to fetch (default 20), \fB\fCspan\-crossref\-members\fR only.
.TP
\fB\fC\-sleep\fR \fIduration\fP
Sleep between requests (default 1s), \fB\fCspan\-crossref\-members\fR only.
.TP
\fB\fC\-q\fR
Suppress logging output, \fB\fCspan\-crossref\-members\fR only.
.TP
\fB\fC\-h\fR
Show usage.
.TP
\fB\fC\-E\fR \fInumerrors\fP
Number of errors to tolerate during processing. \fB\fCspan\-crossref\-snapshot\fR only.
.TP
\fB\fC\-S\fR \fIsize\fP
Buffer size, passed to sort. \fB\fCspan\-crossref\-snapshot\fR only.
.SH EXAMPLES
.PP
List supported formats for conversion to intermediate schema:
.IP
\fB\fCspan\-import \-list\fR
.PP
Convert DOAJ OAI harvest to intermediate schema:
.IP
\fB\fCspan\-import \-i doaj\-oai harvest.xml\fR
.PP
Apply licensing information from a string with streaming input.
.IP
\fB\fCcat intermediate.file | span\-tag \-c '{"DE\-15": {"any": {}}}'\fR
.PP
Apply licensing information from a configuration file to an intermediate schema file.
.IP
\fB\fCspan\-tag \-c <(echo '{"DE\-15": {"any": {}}})' intermediate.file\fR
.PP
There are a couple of content filters available: \fB\fCany\fR, \fB\fCdoi\fR, \fB\fCissn\fR,
\fB\fCpackage\fR, \fB\fCholdings\fR, \fB\fCcollection\fR, \fB\fCsource\fR and \fB\fCsubject\fR\&. These content
filters can be combined with: \fB\fCor\fR, \fB\fCand\fR and \fB\fCnot\fR\&. The configuration can be
seen as an expression forest. The top level keys are the labels, that will be
injected as \fB\fCx.labels\fR into the document, if the filter below the key evaluates
to true.
.PP
The holdings filter configuration can include a list of URLs. As of 0.1.221 the
the "urls" value supports the \fB\fCfile://\fR scheme as well.
.PP
More complex example for a configuration file:
.PP
.RS
.nf
{
  "DE\-14": {
    "or": [
      {
        "and": [
          {
            "source": [
              "55"
            ]
          },
          {
            "holdings": {
              "urls": [
                "http://www.jstor.org/kbart/collections/asii",
                "http://www.jstor.org/kbart/collections/as"
              ]
            }
          }
        ]
      },
      {
        "and": [
          {
            "source": [
              "49"
            ]
          },
          {
            "holdings": {
              "urls": [
                "https://example.com/KBART_DE14",
                "https://example.com/KBART_FREEJOURNALS"
              ]
            }
          },
          {
            "collection": [
              "Turkish Family Physicans Association (CrossRef)",
              "Helminthological Society (CrossRef)",
              "International Association of Physical Chemists (IAPC) (CrossRef)",
              "The Society for Antibacterial and Antifungal Agents, Japan (CrossRef)",
              "Fundacao CECIERJ (CrossRef)"
            ]
          }
        ]
      }
    ]
  }
}
.fi
.RE
.IP
\fB\fCspan\-tag \-c config.json intermediate.file\fR
.PP
List available export formats:
.IP
\fB\fCspan\-export \-list\fR
.PP
Export to a SOLR schema:
.IP
\fB\fCspan\-export \-o solr5vu3 intermediate.file\fR
.PP
Export to Metafacture formeta:
.IP
\fB\fCspan\-export \-o formeta intermediate.file\fR
.PP
Set OA flag (via KBART\-ish file):
.IP
\fB\fCecho '{"rft.issn": ["1234\-1234"], "rft.date": "2000\-01\-01"}' | span\-oa\-filter \-f <(echo $'online_identifier\\n1234\-1234')\fR
.PP
Update labels, for example after a deduplication run with 
.BR groupcover (1):
.IP
\fB\fCecho '{"finc.id": "1"}' | span\-update\-labels \-f <(echo '1,X,Y')\fR
.PP
Create a snapshot of crossref works API message items \-\- more details in \[la]https://git.io/fjeih:\[ra]
.IP
\fB\fCspan\-crossref\-snapshot \-o snapshot.ldj.gz messages.ldj.gz\fR
.PP
The \fB\fCmessages.ldj.gz\fR must contain only the message portion of an crossref API
response \- one per line \- for example:
.IP
\fB\fCcurl \-sL goo.gl/Cq34Bd | jq .message\fR
.PP
Given an intermediate schema file, extract id, source id, doi and labels
(ISIL). Can be fed into 
.BR groupcover (1) 
for deduplication.
.IP
\fB\fCspan\-local\-data < input.ldj > output.tsv\fR
.PP
Example output:
.IP
\fB\fCai\-49\-aHR0cDovL2R4LmRva...    49    10.2307/3102818    DE\-15\-FID    DE\-Ch1    DE\-105\fR
.SH Freezing a filterconfig
.PP
When given a single file containing a number of URLs, it is required to keep
both the file and all URLs it contains for a given point in time (#12021). The
\fB\fCspan\-freeze\fR tool is generic, in that it does not assume any format. It will
create a zip file with the following layout:
.PP
.RS
.nf
/blob
/mapping.json
/files/<hash>
/files/<hash>
\&...
.fi
.RE
.PP
Where \fB\fCblob\fR is the original file containing URLs, \fB\fCmapping.json\fR is a JSON document
containing a SHA1 to URL mapping and the \fB\fCfiles\fR directory contains all
responses, with the filename being the SHA1 of the URL.
.PP
Example usage:
.IP
\fB\fCspan\-freeze \-o frozen.zip < filterconfig.json\fR
.PP
Example for thawing a configuration. The zip file will be decompressed into a
temporary location and the configuration is modified accordingly before tagging
starts.
.IP
\fB\fCspan\-tag \-unfreeze frozen.zip < intermediate.file\fR
.PP
The freeze tool is generic, albeit of limited utility:
.IP
\fB\fCcurl \-sL https://www.heise.de | span\-freeze \-b \-o heise.zip\fR
.SH NEXT ITERATION TAGGING
.PP
In order to simplify processing, we try to get rid of the flexible tree
structure (of the filterconfig) and use a tabular approach turning AMSL into an
sqlite3 database.
.IP
\fB\fCspan\-amsl\-discovery \-db amsl.db \-live https://live.example.technology\fR
.PP
A new program, called \fB\fCspan\-tagger\fR for the moment, can take this DB and use it
to attach records based on the data in both the database and linked holding
files.
.PP
The queries results are cached, otherwise the process would be too slow for
millions of records. Referenced (holding) files are downloaded into
\fB\fC$HOME/.cache/span/\fR (or whatever your \fB\fCXDG_CACHE_HOME\fR is) on the fly. The
various cases are condensed into a single \fB\fCswitch\fR statement.
.IP
\fB\fCspan\-tagger \-db amsl.db < input.is > output.is\fR
.PP
Similar to \fB\fCspan\-tag\fR, we can let the data flow into the index through pipes.
.IP
\fB\fCtaskcat AIIntermediateSchema | span\-tagger \-db amsl.db | span\-export | solrbulk \-server ...\fR
.SH FILES
.PP
Assets (mostly string to string mappings) are compiled into the executable. To
change these mappings, edit the suitable file under
\[la]https://github.com/miku/span/tree/master/assets\[ra], commit and recompile.
.SH DIAGNOSTICS
.PP
Any error (like faulty JSON, IO errors, ...) will lead to an immediate halt.
The packages might contain executables in test, that are not mentioned at all
in this man page.
.PP
To debug a holdings filter, set \fB\fCverbose\fR to \fB\fCtrue\fR to see rejected records and rejection reason:
.PP
.RS
.nf
{
  "DE\-14": {
    "holdings": {
      "verbose": true,
      "urls": [
        "http://www.jstor.org/kbart/collections/asii",
        "http://www.jstor.org/kbart/collections/as"
      ]
    }
  }
}
.fi
.RE
.PP
Example debugging output, record rejected because it's outside licence coverage:
.PP
.RS
.nf
2016/07/14 14:29:45 {
    "document": {
        ...
        "finc.id": "ai\-55\-aHR0cDovL3d3dy5qc3Rvci5vcmcvc3RhYmxlLzEwLjE0MzIxL3JoZXRwdWJsYWZmYS4xOC4xLjAxNjE",
        ...
        "rft.atitle": "Review: Depression: A Public Feeling",
        ...
        "rft.issn": [
            "1094\-8392",
            "1534\-5238"
        ],
        "rft.date": "2015\-04\-01",
        "doi": "10.14321/rhetpublaffa.18.1.0161",
        ...
    },
    "err": "after coverage interval",
    "issn": "1534\-5238",
    "license": {
        "Begin": {
            "Date": "1998\-04\-01",
            "Volume": "1",
            "Issue": "1"
        },
        "End": {
            "Date": "2012\-12\-01",
            "Volume": "15",
            "Issue": "4"
        },
        "Embargo": \-126144000000000000,
        "EmbargoDisallowEarlier": false
    }
}
.fi
.RE
.SH AMSL DISCOVERY API COMPAT
.PP
In December 2018, the AMSL discovery API, required for licensing via span\-tag,
has been shut down. In order to not have to rewrite too much code at this
point, we rebuild a discovery\-like response from the existing endpoints:
\fImetadata_usage\fP, \fIholdingsfiles\fP, \fIcontentfiles\fP and the new
\fIholdings\fIfile\fPconcat\fP\&.
.PP
At the moment (Feb 2019), the following command writes a discovery API like
JSON response to stdout:
.PP
\fB\fCspan\-amsl\-discovery \-live https://live.example.technology\fR
.PP
A tabular output of the API can be generated with \fB\fC\-f\fR, like:
.PP
\fB\fCspan\-amsl\-discovery \-f live https://live.example.technology | head \-10 | cut \-f 1\-5\fR
.PP
.RS
.nf
UBL\-main        DE\-1972 0       sid\-0\-col\-zdb176dch     Digital Concert Hall
UBL\-main        DE\-Mh31 0       sid\-0\-col\-zdb176dch     Digital Concert Hall
UBL\-main        DE\-105  0       lfer    Lizenzfreie Online\-Ressourcen
UBL\-main        DE\-14   0       lfer    Lizenzfreie Online\-Ressourcen
UBL\-main        DE\-15   0       lfer    Lizenzfreie Online\-Ressourcen
UBL\-main        DE\-15\-FID       0       lfer    Lizenzfreie Online\-Ressourcen
UBL\-main        DE\-1972 0       lfer    Lizenzfreie Online\-Ressourcen
UBL\-main        DE\-Bn3  0       lfer    Lizenzfreie Online\-Ressourcen
UBL\-main        DE\-Brt1 0       lfer    Lizenzfreie Online\-Ressourcen
UBL\-main        DE\-Ch1  0       lfer    Lizenzfreie Online\-Ressourcen
.fi
.RE
.SH DEDUPLICATION AGAINST SOLR
.PP
Since 0.1.285, preliminary support for deduplication (DOI) against SOLR to shorten time\-to\-index. Basically:
.PP
.RS
.nf
$ cat file.is | span\-tag \-unfreeze $(taskoutput AMSLFilterConfigFreeze) \-server example.com/solr/biblio \-w 64 \-b 2000 \-verbose > tagged.is
.fi
.RE
.PP
This will take an untagged intermediate schema file, attach all ISIL according
to config (AMSL) and post\-process the document by looking up the DOI in the
given index, checking whether we have a higher prio source for a document and
ISIL \- if so, drop the label, then serialize.
.PP
A hacky way around the fact, that SOLR only supports single document updates, if \fIall\fP fields are stored:
.nr step0 0 1
.RS
.IP \n+[step0]
Drop the source, collection or whatever set from the index.
.IP \n+[step0]
Find the associated intermediate schema files, run span\-tag ... \-server ... and span\-export.
.IP \n+[step0]
Reindex with 
.BR solrbulk (1).
.RE
.PP
If we could generate smaller updates (daily, weekly) per source (or
collection), then a live\-updater could be feasible, albeit generating extra
load on server (\[la]https://i.imgur.com/fkQNGIr.png\[ra]).
.SH BUGS
.PP
Please report bugs to \[la]https://github.com/miku/span/issues\[ra]\&.
.SH AUTHOR
.PP
Martin Czygan \[la]martin.czygan@uni-leipzig.de\[ra]
.SH SEE ALSO
.PP
FINC \[la]https://finc.info\[ra], AMSL \[la]http://amsl.technology/\[ra], intermediate schema \[la]https://github.com/ubleipzig/intermediateschema\[ra], metafacture \[la]https://github.com/culturegraph\[ra], 
.BR jq (1), 
.BR xmlstarlet (1)
