.TH SPAN 1 "JULY 2016" "Leipzig University Library" "Manuals"
.SH NAME
.PP
span\-import, span\-tag, span\-check, span\-export, span\-oa\-filter,
span\-update\-labels, span\-crossref\-snapshot, span\-local\-data, span\-freeze \- intermediate
schema tools
.SH SYNOPSIS
.PP
\fB\fCspan\-import\fR [\fB\fC\-i\fR \fIinput\-format\fP] < \fIfile\fP
.PP
\fB\fCspan\-tag\fR [\fB\fC\-c\fR \fIconfig\fP] < \fIfile\fP
.PP
\fB\fCspan\-export\fR [\fB\fC\-o\fR \fIoutput\-format\fP] < \fIfile\fP
.PP
\fB\fCspan\-check\fR [\fB\fC\-verbose\fR] < \fIfile\fP
.PP
\fB\fCspan\-oa\-filter\fR [\fB\fC\-f\fR \fIfile\fP] < \fIfile\fP
.PP
\fB\fCspan\-update\-labels\fR [\fB\fC\-f\fR \fIfile\fP, \fB\fC\-s\fR \fIseparator\fP] < \fIfile\fP
.PP
\fB\fCspan\-crossref\-snapshot\fR [\fB\fC\-x\fR \fIfile\fP] \-o \fIfile\fP \fIfile\fP
.PP
\fB\fCspan\-local\-data\fR < \fIfile\fP
.PP
\fB\fCspan\-freeze\fR \-o \fIfile\fP < \fIfile\fP
.SH DESCRIPTION
.PP
The \fB\fCspan\fR tools convert to and from an intermediate schema and support
license tagging and quality assurance.
.PP
The intermediate schema is a normalization vehicle, spec:
\[la]https://github.com/ubleipzig/intermediateschema\[ra]
.SH OPTIONS
.TP
\fB\fC\-i\fR \fIformat\fP
Input format. \fB\fCspan\-import\fR only.
.TP
\fB\fC\-o\fR \fIformat\fP
Output format or file. \fB\fCspan\-export\fR, \fB\fCspan\-freeze\fR only..
.TP
\fB\fC\-c\fR \fIconfig\-string\fP or \fIconfig\-file\fP
Configuration string or path to configuration file. \fB\fCspan\-tag\fR only. See
EXAMPLE for a CONFIGURATION FILE.
.TP
\fB\fC\-list\fR
List support formats. \fB\fCspan\-import\fR, \fB\fCspan\-export\fR only.
.TP
\fB\fC\-verbose\fR
More output. \fB\fCspan\-check\fR only.
.TP
\fB\fC\-b\fR \fIN\fP
Batch size. \fB\fCspan\-tag\fR, \fB\fCspan\-check\fR, \fB\fCspan\-export\fR, \fB\fCspan\-crossref\-snapshot\fR only.
.TP
\fB\fC\-w\fR \fIN\fP
Number of workers (defaults to CPU count). \fB\fCspan\-tag\fR, \fB\fCspan\-check\fR, \fB\fCspan\-export\fR only.
.TP
\fB\fC\-cpuprofile\fR \fIpprof\-file\fP
Profiling. \fB\fCspan\-import\fR, \fB\fCspan\-tag\fR, \fB\fCspan\-crossref\-snapshot\fR only.
.TP
\fB\fC\-f\fR
File location (ISSN list or ID,ISIL). \fB\fCspan\-oa\-filter\fR, \fB\fCspan\-update\-labels\fR only.
.TP
\fB\fC\-s\fR
Field separator. \fB\fCspan\-update\-labels\fR only.
.TP
\fB\fC\-v\fR
Show version.
.TP
\fB\fC\-x\fR
Filename to DOI to exclude, one per line. \fB\fCspan\-crossref\-snapshot\fR only.
.TP
\fB\fC\-z\fR
Input is gzip compressed. \fB\fCspan\-crossref\-snapshot\fR only.
.TP
\fB\fC\-h\fR
Show usage.
.SH EXAMPLES
.PP
List supported format for conversion to intermediate schema:
.IP
\fB\fCspan\-import \-list\fR
.PP
Convert DOAJ dump into intermediate schema:
.IP
\fB\fCspan\-import \-i doaj dump.ldj\fR
.PP
Apply licensing information from a string with streaming input.
.IP
\fB\fCcat intermediate.file | span\-tag \-c '{"DE\-15": {"any": {}}}'\fR
.PP
Apply licensing information from a configuration file to an intermediate schema file.
.IP
\fB\fCspan\-tag \-c <(echo '{"DE\-15": {"any": {}}})' intermediate.file\fR
.PP
There are a couple of content filters available: \fB\fCany\fR, \fB\fCdoi\fR, \fB\fCissn\fR,
\fB\fCpackage\fR, \fB\fCholdings\fR, \fB\fCcollection\fR, \fB\fCsource\fR and \fB\fCsubject\fR\&. These content
filters can be combined with: \fB\fCor\fR, \fB\fCand\fR and \fB\fCnot\fR\&. The configuration can be
seen as an expression forest. The top level keys are the labels, that will be
injected as \fB\fCx.labels\fR into the document, if the filter below the key evaluates
to true.
.PP
More complex example for a configuration file:
.PP
.RS
.nf
{
  "DE\-14": {
    "or": [
      {
        "and": [
          {
            "source": [
              "55"
            ]
          },
          {
            "holdings": {
              "urls": [
                "http://www.jstor.org/kbart/collections/asii",
                "http://www.jstor.org/kbart/collections/as"
              ]
            }
          }
        ]
      },
      {
        "and": [
          {
            "source": [
              "49"
            ]
          },
          {
            "holdings": {
              "urls": [
                "https://example.com/KBART_DE14",
                "https://example.com/KBART_FREEJOURNALS"
              ]
            }
          },
          {
            "collection": [
              "Turkish Family Physicans Association (CrossRef)",
              "Helminthological Society (CrossRef)",
              "International Association of Physical Chemists (IAPC) (CrossRef)",
              "The Society for Antibacterial and Antifungal Agents, Japan (CrossRef)",
              "Fundacao CECIERJ (CrossRef)"
            ]
          }
        ]
      }
    ]
  }
}
.fi
.RE
.IP
\fB\fCspan\-tag \-c config.json intermediate.file\fR
.PP
List available export formats:
.IP
\fB\fCspan\-export \-list\fR
.PP
Export to a SOLR schema:
.IP
\fB\fCspan\-export \-o solr5vu3 intermediate.file\fR
.PP
Export to Metafacture formeta:
.IP
\fB\fCspan\-export \-o formeta intermediate.file\fR
.PP
Set OA flag (via KBART\-ish file):
.IP
\fB\fCecho '{"rft.issn": ["1234\-1234"], "rft.date": "2000\-01\-01"}' | span\-oa\-filter \-f <(echo $'online_identifier\\n1234\-1234')\fR
.PP
Update labels:
.IP
\fB\fCecho '{"finc.record_id": "1"}' | span\-update\-labels \-f <(echo '1,X,Y')\fR
.PP
Create a snapshot of crossref works API message items:
.IP
\fB\fCspan\-crossref\-snapshot \-o snapshot.ldj.gz messages.ldj.gz\fR
.PP
The \fB\fCmessages.ldj.gz\fR must contain only the message portion of an crossref API
response \- one per line \- for example:
.IP
\fB\fCcurl \-sL goo.gl/Cq34Bd | jq .message\fR
.PP
Given an intermediate schema file, extract record id, source id, doi and labels
(ISIL). Can be fed into 
.BR groupcover (1) 
for deduplication.
.IP
\fB\fCspan\-local\-data < input.ldj > output.tsv\fR
.PP
Example output:
.IP
\fB\fCai\-49\-aHR0cDovL2R4LmRva...    49    10.2307/3102818    DE\-15\-FID    DE\-Ch1    DE\-105\fR
.SH Freezing a filterconfig
.PP
When given a single file containing a number of URLs, it is required to keep
both the file and all URLs it contains for a given point in time. The
\fB\fCspan\-freeze\fR tool is generic, in that it does not assume any format. It will
create a zip file with the following layout:
.PP
.RS
.nf
/blob
/mapping.json
/files/<hash>
/files/<hash>
\&...
.fi
.RE
.PP
Where \fB\fCblob\fR is the original file containing URLs, \fB\fCmapping\fR is a JSON document
containing a SHA1 to URL mapping and the \fB\fCfiles\fR directory contains all
responses, with the filename being the SHA1 of the URL.
.PP
Example usage:
.IP
\fB\fCspan\-freeze \-o frozen.zip < filterconfig.json\fR
.PP
Thaw:
.IP
\fB\fCspan\-tag \-unfreeze frozen.zip < intermediate.file\fR
.SH FILES
.PP
Assets (mostly string to string mappings) are compiled into the executable. To
change these mappings, edit the suitable file under
\[la]https://github.com/miku/span/tree/master/assets\[ra], commit and recompile.
.SH DIAGNOSTICS
.PP
Any error (like faulty JSON, IO errors, ...) will lead to an immediate halt.
.PP
To debug a holdings filter, set \fB\fCverbose\fR to \fB\fCtrue\fR to see rejected records and rejection reason:
.PP
.RS
.nf
{
  "DE\-14": {
    "holdings": {
      "verbose": true,
      "urls": [
        "http://www.jstor.org/kbart/collections/asii",
        "http://www.jstor.org/kbart/collections/as"
      ]
    }
  }
}
.fi
.RE
.PP
Example debugging output, record rejected because it's outside licence coverage:
.PP
.RS
.nf
2016/07/14 14:29:45 {
    "document": {
        ...
        "finc.record_id": "ai\-55\-aHR0cDovL3d3dy5qc3Rvci5vcmcvc3RhYmxlLzEwLjE0MzIxL3JoZXRwdWJsYWZmYS4xOC4xLjAxNjE",
        ...
        "rft.atitle": "Review: Depression: A Public Feeling",
        ...
        "rft.issn": [
            "1094\-8392",
            "1534\-5238"
        ],
        "rft.date": "2015\-04\-01",
        "doi": "10.14321/rhetpublaffa.18.1.0161",
        ...
    },
    "err": "after coverage interval",
    "issn": "1534\-5238",
    "license": {
        "Begin": {
            "Date": "1998\-04\-01",
            "Volume": "1",
            "Issue": "1"
        },
        "End": {
            "Date": "2012\-12\-01",
            "Volume": "15",
            "Issue": "4"
        },
        "Embargo": \-126144000000000000,
        "EmbargoDisallowEarlier": false
    }
}
.fi
.RE
.SH BUGS
.PP
Please report bugs to \[la]https://github.com/miku/span/issues\[ra]\&.
.SH AUTHOR
.PP
Martin Czygan \[la]martin.czygan@uni-leipzig.de\[ra]
.SH SEE ALSO
.PP
FINC \[la]https://finc.info\[ra], AMSL \[la]http://amsl.technology/\[ra], intermediate schema \[la]https://github.com/ubleipzig/intermediateschema\[ra], metafacture \[la]https://github.com/culturegraph\[ra], 
.BR jq (1), 
.BR xmlstarlet (1)
