package doaj

// LanguageNames maps DOAJ specific language strings to ISO identifiers.
var LanguageNames = map[string]string{
	"AB": "abk",
	"Aboriginal languages": "und",
	"AF":                        "afr",
	"Afrikaans":                 "afr",
	"all EU official languages": "und",
	"all Slavic languages":      "sla",
	"AR":                   "ara",
	"Arabic":               "ara",
	"Armenian":             "arm",
	"Azeri":                "aze",
	"Bahasa Indonesia":     "ind",
	"Bahasa Malaysia":      "mal",
	"Bahasa Malaysian":     "mal",
	"Basque":               "baq",
	"Belarusian":           "bel",
	"Bengali":              "ben",
	"BG":                   "bul",
	"BO":                   "tib",
	"Bosnian":              "bos",
	"Bulgarian":            "bul",
	"CA":                   "cat",
	"Castilian":            "spa",
	"Catalan":              "cat",
	"Catalonian":           "cat",
	"Chinese":              "zho",
	"Croatian":             "hrv",
	"CS":                   "ces",
	"Czech":                "ces",
	"DA":                   "dan",
	"Danish":               "dan",
	"DE":                   "deu",
	"Deutsch":              "deu",
	"Dutch":                "nld",
	"Dutch/Flemish":        "nld",
	"EN":                   "eng",
	"Enghlish":             "eng",
	"Engilish":             "eng",
	"Engkish":              "eng",
	"Engliah":              "eng",
	"Englisch":             "eng",
	"English (UK)":         "eng",
	"English and Italian":  "und",
	"English":              "eng",
	"english":              "eng",
	"ES":                   "spa",
	"Espanhol":             "spa",
	"Esperanto":            "epo",
	"Estonian":             "est",
	"ET":                   "est",
	"Euskera":              "baq",
	"FA":                   "fas",
	"Farsi":                "fas",
	"FI":                   "fin",
	"Filipino":             "fil",
	"Finnish":              "fin",
	"FR":                   "fra",
	"French":               "fra",
	"Galician":             "glg",
	"Galizian":             "glg",
	"Geman":                "und",
	"Georgian":             "geo",
	"German / English":     "und",
	"German":               "deu",
	"GL":                   "glg",
	"Greek":                "ell",
	"Hebrew":               "heb",
	"Hindi":                "hin",
	"HR":                   "hrv",
	"HU":                   "hun",
	"Hungarian":            "hun",
	"Icelandic":            "ice",
	"ID":                   "ind",
	"Indonesia":            "ind",
	"Indonesian":           "ind",
	"Isipedi":              "und",
	"IT":                   "ita",
	"Italian":              "ita",
	"JA":                   "jpn",
	"Japanese":             "jpn",
	"KiSwahili":            "swa",
	"Kiswahili":            "swa",
	"KK":                   "kaz",
	"Korean":               "kor",
	"Latin":                "lat",
	"Latvian":              "lav",
	"Lithuanian":           "lit",
	"LT":                   "lit",
	"Macedonian":           "mac",
	"Malay":                "msa",
	"Maori":                "mri",
	"Marathi":              "mar",
	"Montenegrian":         "mis",
	"Multilingual":         "und",
	"multiple languages":   "und",
	"NB":                   "nob",
	"NL":                   "nld",
	"NO":                   "nor",
	"Norwegian":            "nor",
	"Norweigan":            "nor",
	"Persian":              "fas",
	"Philippine languages": "phi",
	"PL":                  "pol",
	"Polish":              "pol",
	"Portoguese":          "por",
	"Portugese":           "por",
	"Portugues":           "por",
	"portuguese":          "por",
	"Portuguese":          "por",
	"Potugu\u00eas":       "por",
	"PT":                  "por",
	"RO":                  "rum",
	"Romanian":            "ron",
	"RU":                  "rus",
	"Rumanian":            "rum",
	"Russian":             "rus",
	"Sanskrit":            "san",
	"Scots":               "gla",
	"Serbian":             "srp",
	"Serbo-Croatian":      "hbs",
	"SK":                  "slo",
	"Slavic languages":    "sla",
	"Slovak":              "slk",
	"Slovakian":           "slk",
	"Slovenan":            "slv",
	"Slovene":             "slv",
	"Slovenian":           "slv",
	"Spain":               "spa",
	"spanish":             "spa",
	"Spanish":             "spa",
	"Spanish. Portuguese": "por",
	"Spannish":            "spa",
	"SR":                  "srp",
	"SV":                  "swe",
	"Swahili":             "swa",
	"Swedish":             "swe",
	"Thai":                "tha",
	"TR":                  "tur",
	"Turkish":             "tur",
	"Turskish":            "tur",
	"Uitoto":              "huu",
	"UK":                  "eng",
	"Ukrainian":           "ukr",
	"Ukranian":            "ukr",
	"Urdu":                "urd",
	"Vietnamese":          "vie",
	"Xhosa":               "xho",
	"Yoruba":              "yor",
	"ZH":                  "chi",
}
