package doaj

import "github.com/miku/span/container"

var LanguageMap = container.StringMap{
	"English":            "eng",
	"Spanish":            "spa",
	"Portuguese":         "por",
	"French":             "fra",
	"German":             "deu",
	"Italian":            "ita",
	"Russian":            "rus",
	"Turkish":            "tur",
	"EN":                 "eng",
	"Chinese":            "zho",
	"Serbian":            "srp",
	"Persian":            "fas",
	"Dutch":              "nld",
	"Ukrainian":          "ukr",
	"Romanian":           "ron",
	"Afrikaans":          "afr",
	"ES":                 "spa",
	"Polish":             "pol",
	"Indonesian":         "ind",
	"Croatian":           "hrv",
	"Catalan":            "cat",
	"Czech":              "ces",
	"Slovak":             "slk",
	"PT":                 "por",
	"RU":                 "rus",
	"Norwegian":          "nor",
	"Hindi":              "hin",
	"Marathi":            "mar",
	"Slovenian":          "slv",
	"Arabic":             "ara",
	"Danish":             "dan",
	"Swedish":            "swe",
	"Greek":              "ell",
	"FR":                 "fra",
	"Thai":               "tha",
	"Lithuanian":         "lit",
	"Farsi":              "fas",
	"Malay":              "msa",
	"multiple languages": "und",
	"UK":                 "eng",
	"Isipedi":            "und",
	"Bahasa Indonesia":   "ind",
	"Galician":           "glg",
	"AR":                 "ara",
	"Castilian":          "spa",
	"Portugese":          "por",
	"Slovene":            "slv",
	"TR":                 "tur",
	"Estonian":           "est",
	"Bulgarian":          "bul",
	"english":            "eng",
	"spanish":            "spa",
	"portuguese":         "por",
	"Bosnian":            "bos",
	"Macedonian":         "mac",
	"ID":                 "ind",
	"Rumanian":           "rum",
	"IT":                 "ita",
	"Spain":              "spa",
	"CS":                 "ces",
	"SK":                 "slo",
	"Hungarian":          "hun",
	"SR":                 "srp",
	"Ukranian":           "ukr",
	"Korean":             "kor",
	"KK":                 "kaz",
	"ZH":                 "chi",
	"Icelandic":          "ice",
	"ET":                 "est",
	"Slavic languages":   "sla",
	"DE":                 "deu",
	"HU":                 "hun",
	"English (UK)":       "eng",
	"Finnish":            "fin",
	"Filipino":           "fil",
	"Japanese":           "jpn",
	"FA":                 "fas",
	"BO":                 "tib",
	"Basque":             "baq",
	"BG":                 "bul",
	"HR":                 "hrv",
	"Hebrew":             "heb",
	"Turskish":           "tur",
	"Engkish":            "eng",
	"Bengali":            "ben",
	"Xhosa":              "xho",
	"Uitoto":             "huu",
	"Slovakian":          "slk",
	"Dutch/Flemish":      "nld",
	"PL":                 "pol",
	"Norweigan":          "nor",
	"LT":                 "lit",
	"Indonesia":          "ind",
	"FI":                 "fin",
	"RO":                 "rum",
	"Multilingual":       "und",
	"Serbo-Croatian":     "hbs",
	"CA":                 "cat",
	"Latvian":            "lav",
	"NO":                 "nor",
	"Portoguese":         "por",
	"Latin":              "lat",
	"Bahasa Malaysia":    "mal",
	"Engilish":           "eng",
	"SV":                 "swe",
	"NL":                 "nld",
	"DA":                 "dan",
	"AF":                 "afr",
	"all Slavic languages":      "sla",
	"Swahili":                   "swa",
	"Georgian":                  "geo",
	"Catalonian":                "cat",
	"all EU official languages": "und",
	"Yoruba":                    "yor",
	"Vietnamese":                "vie",
	"Urdu":                      "urd",
	"Spannish":                  "spa",
	"Spanish. Portuguese":       "por",
	"Slovenan":                  "slv",
	"Scots":                     "gla",
	"Sanskrit":                  "san",
	"Potuguês":                  "por",
	"Portugues":                 "por",
	"Philippine languages":      "phi",
	"NB":                   "nob",
	"Montenegrian":         "mis",
	"Maori":                "mri",
	"Kiswahili":            "swa",
	"KiSwahili":            "swa",
	"JA":                   "jpn",
	"German / English":     "und",
	"Geman":                "und",
	"Galizian":             "glg",
	"GL":                   "glg",
	"Euskera":              "baq",
	"Esperanto":            "epo",
	"Espanhol":             "spa",
	"English and Italian":  "und",
	"Englisch":             "eng",
	"Engliah":              "eng",
	"Enghlish":             "eng",
	"Deutsch":              "deu",
	"Belarusian":           "bel",
	"Bahasa Malaysian":     "mal",
	"Azeri":                "aze",
	"Armenian":             "arm",
	"Aboriginal languages": "und",
	"AB": "abk",
}
